name = "personal-flashcards"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "flashcards-db"
database_id = "80c078dc-4451-4e31-8752-d50de062f827"
migrations_dir = "migrations"

[vars]
ALLOWED_EMAIL = "2412nguyenhoanghai@gmail.com, hai@example.com"
APP_ENV = "production"
