import { w } from './helper.js';

export const unitsPart3 = [
  {
    id: 23,
    title: 'Nhà hàng, Ẩm thực & Dịch vụ tiệc công ty (Dining & Corporate Catering)',
    words: [
      w('catering', 'n', '/ˈkeɪtərɪŋ/', 'dịch vụ nấu nướng và phục vụ tiệc', 'The hotel provides executive catering services for the annual gala dinner.'),
      w('banquet', 'n', '/ˈbæŋkwɪt/', 'bữa tiệc lớn trang trọng, tiệc chiêu đãi', 'Over three hundred foreign ambassadors attended the state banquet at City Hall.'),
      w('culinary', 'adj', '/ˈkʌlɪnəri/', 'thuộc về nghệ thuật ẩm thực, nấu nướng', 'The executive chef demonstrated extraordinary culinary expertise during the tasting.'),
      w('beverage', 'n', '/ˈbevərɪdʒ/', 'đồ uống, thức uống giải khát', 'Complimentary beverages and hors d’oeuvres were served prior to the main course.'),
      w('dietary', 'adj', '/ˈdaɪətəri/', 'thuộc chế độ ăn kiêng, dinh dưỡng', 'Please inform the catering staff in advance of any special dietary restrictions.'),
      w('appetizer', 'n', '/ˈæpɪtaɪzə(r)/', 'món khai vị mở đầu bữa ăn', 'The dinner began with a delightful seafood appetizer and sparkling wine.'),
      w('entree', 'n', '/ˈɒntreɪ/', 'món ăn chính của bữa tiệc', 'Guests had a choice between grilled salmon and tender roast beef for their entree.'),
      w('dessert', 'n', '/dɪˈzɜːt/', 'món tráng miệng ngọt sau bữa ăn', 'A decadent chocolate mousse was served as the evening’s concluding dessert.'),
      w('table booking', 'n phr', '/ˈteɪbl ˈbʊkɪŋ/', 'sự đặt bàn tiệc trước', 'Call ahead to confirm your table booking if your party exceeds eight guests.'),
      w('ingredient', 'n', '/ɪnˈɡriːdiənt/', 'nguyên liệu thực phẩm chế biến món ăn', 'The restaurant prides itself on sourcing fresh organic ingredients from local farms.'),
      w('chef', 'n', '/ʃef/', 'bếp trưởng chuyên nghiệp', 'The renowned Michelin-starred chef personally curated the six-course tasting menu.'),
      w('delicacy', 'n', '/ˈdelɪkəsi/', 'sơn hào hải vị, món đặc sản quý hiếm', 'Truffles and caviar are regarded as luxurious delicacies across high-end restaurants.'),
      w('buffet', 'n', '/ˈbʊfeɪ/', 'bữa ăn tự chọn buffet', 'The international breakfast buffet features pastries, fresh fruit, and hot omelets.'),
      w('sommelier', 'n', '/sɒˈmelieɪ/', 'chuyên gia tư vấn rượu vang nhà hàng', 'The sommelier recommended an exquisite Pinot Noir to pair with the venison.'),
      w('cordiality', 'n', '/ˌkɔːdiˈæləti/', 'sự nồng hậu, thân tình tiếp đón', 'The restaurant manager welcomed our guests with genuine warmth and cordiality.'),
      w('refreshment', 'n', '/rɪˈfreʃmənt/', 'đồ ăn nhẹ và nước giải khát giữa giờ', 'Light refreshments will be served in the foyer during the 15-minute meeting intermission.'),
      w('gratuity', 'n', '/ɡrəˈtjuːəti/', 'tiền boa, tiền tip cho nhân viên phục vụ', 'An 18% gratuity is automatically added to the final bill for parties of six or more.'),
      w('diner', 'n', '/ˈdaɪnə(r)/', 'thực khách thưởng thức bữa ăn', 'Discerning diners praised the balance of flavors in the chef’s signature duck breast.'),
      w('reception', 'n', '/rɪˈsepʃn/', 'tiệc chiêu đãi chào mừng khách mời', 'A welcome reception will be held on the terrace overlooking the harbor.'),
      w('takeout', 'n, adj', '/ˈteɪkaʊt/', 'đồ ăn mang về nhà', 'Busy office workers often order takeout lunches from the neighboring noodle bar.'),
      w('cutlery', 'n', '/ˈkʌtləri/', 'bộ dao muỗng nĩa dùng bữa', 'Tables were set with gleaming silver cutlery and pressed linen napkins.'),
      w('palatable', 'adj', '/ˈpælətəbl/', 'ngon miệng, hợp khẩu vị', 'Even picky clients found the fusion menu dishes remarkably palatable.'),
      w('vegetarian', 'adj, n', '/ˌvedʒəˈteəriən/', 'chay, món ăn không thịt cá', 'The banquet menu offers delicious vegetarian and vegan options for attendees.'),
      w('seasoning', 'n', '/ˈsiːznɪŋ/', 'gia vị nêm nếm món ăn', 'The soup lacked sufficient seasoning and needed a pinch of sea salt and pepper.'),
      w('wholesome', 'adj', '/ˈhəʊlsəm/', 'bổ dưỡng, lành mạnh cho sức khỏe', 'The company cafeteria emphasizes wholesome meals made with unrefined whole grains.'),
      w('leftovers', 'n (pl)', '/ˈleftəʊvəz/', 'thức ăn thừa sau bữa tiệc', 'Uneaten banquet leftovers were packed in sustainable containers and donated.'),
      w('ambiance', 'n', '/ˈæmbiəns/', 'không gian bầu không khí của nhà hàng', 'Soft jazz music and dim lighting created an elegant, intimate ambiance.'),
      w('tableware', 'n', '/ˈteɪblweə(r)/', 'đồ dùng bàn ăn (bát đĩa ly tách)', 'The hotel purchased fine porcelain tableware for its presidential banquet hall.'),
      w('condiment', 'n', '/ˈkɒndɪmənt/', 'đồ chấm, gia vị ăn kèm (tương, sốt)', 'Condiments such as mustard, mayonnaise, and ketchup are available at the counter.'),
      w('caterer', 'n', '/ˈkeɪtərə(r)/', 'công ty/đơn vị nhận nấu tiệc lưu động', 'We hired an award-winning local caterer to supply food for the product launch.')
    ]
  },
  {
    id: 24,
    title: 'Bảo hiểm, Quản trị rủi ro & Bồi thường thiệt hại (Insurance & Claims)',
    words: [
      w('policy', 'n', '/ˈpɒləsi/', 'hợp đồng/chính sách bảo hiểm', 'Please review the exclusions listed on page four of your commercial property policy.'),
      w('premium', 'n', '/ˈpriːmiəm/', 'phí đóng bảo hiểm định kỳ', 'Installing advanced sprinkler systems lowered the company’s annual insurance premium.'),
      w('deductible', 'n', '/dɪˈdʌktəbl/', 'mức khấu trừ miễn thường tự chi trả', 'The policyholder must pay a $500 deductible before the insurer covers auto repair costs.'),
      w('claim', 'n, v', '/kleɪm/', 'hồ sơ yêu cầu bồi thường bảo hiểm; đòi bồi thường', 'The warehouse filed a fire damage claim with their insurance provider yesterday.'),
      w('coverage', 'n', '/ˈkʌvərɪdʒ/', 'phạm vi bảo hiểm chi trả bảo vệ', 'Standard health insurance provides full coverage for hospitalization and prescription medicine.'),
      w('underwriter', 'n', '/ˈʌndəraɪtə(r)/', 'chuyên viên thẩm định rủi ro bảo hiểm', 'The insurance underwriter evaluated flood zone risks before approving the policy.'),
      w('adjuster', 'n', '/əˈdʒʌstə(r)/', 'giám định viên xác định tổn thất bảo hiểm', 'A claims adjuster inspected the storm-damaged roof to calculate compensation.'),
      w('third-party liability', 'n phr', '/θɜːd ˈpɑːti ˌlaɪəˈbɪləti/', 'trách nhiệm dân sự đối với bên thứ ba', 'Commercial auto policies must provide comprehensive third-party liability coverage.'),
      w('indemnity payout', 'n phr', '/ɪnˈdemnəti ˈpeɪaʊt/', 'khoản chi trả bồi thường tổn thất', 'The insurer disbursed a $2 million indemnity payout following the fire assessment.'),
      w('indemnity', 'n', '/ɪnˈdemnəti/', 'sự bồi thường tổn thất, bảo đảm bồi hoàn', 'The indemnity clause protects the software firm from third-party copyright claims.'),
      w('actuary', 'n', '/ˈæktʃuəri/', 'chuyên viên tính toán rủi ro thống kê', 'Actuaries calculate life expectancy and probability distributions to price annuity policies.'),
      w('all-inclusive policy', 'n phr', '/ˌɔːl ɪnˈkluːsɪv ˈpɒləsi/', 'hợp đồng bảo hiểm trọn gói mọi rủi ro', 'We purchased an all-inclusive policy covering fire, flood, and vandalism.'),
      w('beneficiary', 'n', '/ˌbenɪˈfɪʃəri/', 'người thụ hưởng quyền lợi bảo hiểm', 'Employees can designate a spouse or children as primary beneficiaries on their life plan.'),
      w('lapse', 'v, n', '/læps/', 'mất hiệu lực do không đóng phí bảo hiểm', 'If you fail to pay your quarterly premium within thirty days, coverage will lapse.'),
      w('out-of-pocket expense', 'n phr', '/ˌaʊt əv ˈpɒkɪt ɪkˈspens/', 'chi phí tự bỏ tiền túi chi trả trước', 'Prescription drug coverage helps policyholders minimize out-of-pocket expenses.'),
      w('dispute arbitration', 'n phr', '/dɪˈspjuːt ˌɑːbɪˈtreɪʃn/', 'phân xử giải quyết tranh chấp bảo hiểm', 'Disagreements regarding claim sizes were submitted to binding dispute arbitration.'),
      w('appraise', 'v', '/əˈpreɪz/', 'định giá tài sản để mua bảo hiểm', 'An independent jeweler appraised the vintage diamond necklace at $80,000.'),
      w('rider', 'n', '/ˈraɪdə(r)/', 'điều khoản bổ sung hợp đồng bảo hiểm', 'We added an earthquake rider to our existing California homeowners policy.'),
      w('annuity', 'n', '/əˈnjuːəti/', 'tiền bảo hiểm niên kim chi trả hằng năm', 'Retirees often purchase annuities to ensure a guaranteed steady income stream.'),
      w('culpability', 'n', '/ˌkʌlpəˈbɪləti/', 'sự có lỗi, trách nhiệm gây tai nạn', 'The accident investigation revealed no evidence of criminal driver culpability.'),
      w('co-payment', 'n', '/ˈkəʊ peɪmənt/', 'khoản đồng chi trả viện phí của người bệnh', 'Each doctor visit requires a modest $20 co-payment under our preferred provider network.'),
      w('underwrite risk', 'phr', '/ˌʌndəraɪt rɪsk/', 'bảo lãnh gánh chịu rủi ro bảo hiểm', 'Lloyd’s of London agrees to underwrite risk for complex marine shipping operations.'),
      w('exclusions', 'n (pl)', '/ɪkˈskluːʒnz/', 'các trường hợp loại trừ bảo hiểm không đền', 'Flood damage caused by tsunamis falls under explicit policy exclusions.'),
      w('catastrophe', 'n', '/kəˈtæstrəfi/', 'thảm họa tự nhiên quy mô khổng lồ', 'Reinsurance companies absorb the crushing financial blow of major hurricanes and catastrophes.'),
      w('term life', 'n phr', '/tɜːm laɪf/', 'bảo hiểm nhân thọ có thời hạn', 'A 20-year term life policy provides affordable protection while children grow up.'),
      w('assessment', 'n', '/əˈsesmənt/', 'sự đánh giá mức độ rủi ro/tổn thất', 'Engineers performed a thorough risk assessment of the offshore drilling platform.'),
      w('appraiser', 'n', '/əˈpreɪzə(r)/', 'chuyên viên thẩm định giá trị tổn thất', 'The certified auto appraiser estimated repair costs for the crushed front bumper.'),
      w('claimant', 'n', '/ˈkleɪmənt/', 'người nộp đơn đòi tiền bảo hiểm', 'The claimant supplied photographic proof and police records to substantiate his case.'),
      w('subrogate', 'v', '/ˈsʌbrəɡeɪt/', 'thế quyền truy đòi bên thứ ba gây lỗi', 'After compensating the driver, the insurance company subrogated against the guilty trucker.'),
      w('underinsured', 'adj', '/ˌʌndərɪnˈʃʊəd/', 'mua bảo hiểm dưới giá trị thực tài sản', 'Many coastal homeowners discovered they were critically underinsured following the storm.')
    ]
  },
  {
    id: 25,
    title: 'Truyền thông đại chúng, Báo chí & Quan hệ công chúng (Media & PR)',
    words: [
      w('press release', 'n phr', '/pres rɪˈliːs/', 'thông cáo báo chí gửi truyền thông', 'The corporate PR team issued a formal press release announcing the historic merger.'),
      w('spokesperson', 'n', '/ˈspəʊkspɜːsn/', 'người phát ngôn đại diện chính thức', 'An official company spokesperson denied the rumors during a televised interview.'),
      w('media blitz', 'n phr', '/ˈmiːdiə blɪts/', 'chiến dịch phủ sóng truyền thông ồ ạt', 'The movie studio launched a nationwide media blitz prior to the summer premiere.'),
      w('public relations (PR)', 'n phr', '/ˌpʌblɪk rɪˈleɪʃnz/', 'ngành quan hệ công chúng', 'Effective public relations strategies build goodwill and safeguard corporate reputation.'),
      w('broadcast', 'v, n', '/ˈbrɔːdkɑːst/', 'phát sóng truyền hình/radio; chương trình phát', 'The CEO’s live address was broadcast globally via streaming video and satellite.'),
      w('journalist', 'n', '/ˈdʒɜːnəlɪst/', 'nhà báo, phóng viên chuyên nghiệp', 'Investigative journalists uncovered irregular financial reporting at the conglomerate.'),
      w('editorial', 'n, adj', '/ˌedɪˈtɔːriəl/', 'bài xã luận; thuộc ban biên tập', 'The business magazine published an insightful editorial on automated manufacturing.'),
      w('disseminate news', 'phr', '/dɪˈsemɪneɪt njuːz/', 'phổ biến thông tin tin tức rộng rãi', 'PR wire services help businesses disseminate news releases to global newsrooms.'),
      w('subscriber', 'n', '/səbˈskraɪbə(r)/', 'người đăng ký mua báo/dịch vụ dài hạn', 'Digital news subscribers enjoy ad-free reading and unlimited archive access.'),
      w('headline', 'n', '/ˈhedlaɪn/', 'tiêu đề trang nhất, dòng tít nổi bật', 'The sensational corporate scandal dominated newspaper headlines for weeks.'),
      w('press conference', 'n phr', '/pres ˈkɒnfərəns/', 'buổi họp báo với giới truyền thông', 'Reporters gathered in the main auditorium for an emergency press conference at noon.'),
      w('circulation', 'n', '/ˌsɜːkjəˈleɪʃn/', 'lượng phát hành ấn phẩm báo/tạp chí', 'The newspaper has the highest morning circulation of any daily in the metropolitan area.'),
      w('media outlet', 'n phr', '/ˈmiːdiə ˈaʊtlet/', 'cơ quan báo chí, kênh truyền thông', 'The campaign launched simultaneously across digital channels and traditional media outlets.'),
      w('brand ambassadorship', 'n phr', '/brænd æmˈbæsədəʃɪp/', 'vai trò đại sứ thương hiệu', 'The tennis champion signed a lucrative three-year brand ambassadorship deal.'),
      w('publicity', 'n', '/pʌbˈlɪsəti/', 'sự chú ý của công chúng, tiếng vang truyền thông', 'The promotional stunt generated massive free publicity across all major social networks.'),
      w('leak', 'v, n', '/liːk/', 'tiết lộ thông tin mật ra ngoài; sự rò rỉ', 'Confidential design specifications were leaked to industry bloggers prior to the launch.'),
      w('correspondent', 'n', '/ˌkɒrəˈspɒndənt/', 'phóng viên thường trú nước ngoài', 'Our senior economic correspondent reported live from the World Economic Forum in Davos.'),
      w('retraction', 'n', '/rɪˈtrækʃn/', 'sự cải chính, rút lại thông tin sai sự thật', 'The tabloid was forced to print a front-page retraction and pay substantial libel damages.'),
      w('feature article', 'n phr', '/ˈfiːtʃər ˈɑːtɪkl/', 'bài viết chuyên đề đặc sắc trên báo', 'The tech magazine ran an eight-page feature article on our startup’s renewable battery.'),
      w('sound bite', 'n phr', '/saʊnd baɪt/', 'đoạn trích phát biểu ngắn đắt giá', 'Politicians frequently rehearse memorable sound bites for the evening news broadcasts.'),
      w('exclusive', 'adj, n', '/ɪkˈskluːsɪv/', 'tin độc quyền; thông tin dành riêng', 'The financial journal scored an exclusive interview with the reclusive hedge fund founder.'),
      w('pundit', 'n', '/ˈpʌndɪt/', 'chuyên gia bình luận thời sự/kinh tế', 'Television pundits debated the long-term impact of rising central bank interest rates.'),
      w('libel', 'n, v', '/ˈlaɪbl/', 'tội phỉ báng, bôi nhọ danh dự trên báo chí', 'The celebrity sued the magazine publisher for defamatory libel after false allegations.'),
      w('briefing', 'n', '/ˈbriːfɪŋ/', 'buổi họp thông báo tóm tắt thông tin ngắn', 'The press secretary conducts daily press briefings in the White House briefing room.'),
      w('spin', 'n, v', '/spɪn/', 'sự bóp méo hướng nhìn truyền thông có lợi', 'PR specialists attempted to put a positive spin on the declining quarterly profits.'),
      w('disclose', 'v', '/dɪsˈkləʊz/', 'tiết lộ, công khai với công chúng', 'Publicly traded companies are legally required to disclose material merger talks promptly.'),
      w('censorship', 'n', '/ˈsensəʃɪp/', 'sự kiểm duyệt nội dung trước khi xuất bản', 'Strict government censorship prevented reporters from broadcasting footage of the protest.'),
      w('manuscript', 'n', '/ˈmænjuskrɪpt/', 'bản thảo tác phẩm trước khi in ấn', 'The renowned business author delivered his final book manuscript to the publisher.'),
      w('op-ed', 'n', '/ˌɒp ˈed/', 'bài bình luận của cộng tác viên khách mời', 'The Nobel laureate penned a provocative op-ed on modern income inequality.'),
      w('telecast', 'n, v', '/ˈtelɪkɑːst/', 'chương trình phát hình trên truyền hình', 'Millions of viewers tuned in to watch the live telecast of the championship match.')
    ]
  },
  {
    id: 26,
    title: 'Môi trường, Năng lượng sạch & Phát triển bền vững (Environment & Sustainability)',
    words: [
      w('renewable', 'adj', '/rɪˈnjuːəbl/', 'tái tạo được (năng lượng gió, mặt trời)', 'The nation pledged to generate 80% of its electricity from renewable sources by 2035.'),
      w('sustainability', 'n', '/səˌsteɪnəˈbɪləti/', 'sự phát triển bền vững, thân thiện sinh thái', 'Corporate sustainability initiatives reduce carbon emissions while conserving water.'),
      w('emission', 'n', '/ɪˈmɪʃn/', 'khí thải độc hại xả ra môi trường', 'Automobile manufacturers are under legal mandate to slash harmful vehicle tailpipe emissions.'),
      w('conservation', 'n', '/ˌkɒnsəˈveɪʃn/', 'sự bảo tồn tài nguyên thiên nhiên', 'Energy conservation practices at headquarters cut monthly utility bills by 18 percent.'),
      w('biodegradable', 'adj', '/ˌbaɪəʊdɪˈɡreɪdəbl/', 'tự phân hủy sinh học trong đất', 'The retail chain replaced conventional plastic carrier bags with biodegradable cornstarch bags.'),
      w('carbon footprint', 'n phr', '/ˌkɑːbən ˈfʊtprɪnt/', 'lượng phát thải khí nhà kính (dấu chân carbon)', 'Commuting by public transit rather than personal vehicles significantly shrinks your carbon footprint.'),
      w('solar panel', 'n phr', '/ˈsəʊlə ˈpænl/', 'tấm pin năng lượng mặt trời', 'High-efficiency solar panels installed on factory rooftops supply half of daylight energy needs.'),
      w('wind turbine', 'n phr', '/wɪnd ˈtɜːbaɪn/', 'tuabin gió phát điện', 'Offshore wind turbines generate enormous amounts of clean electricity off the northern coast.'),
      w('pollutant', 'n', '/pəˈluːtənt/', 'chất gây ô nhiễm môi trường', 'Industrial chimneys are outfitted with scrubbers to trap particulate pollutants.'),
      w('pollutant emission', 'n phr', '/pəˈluːtənt ɪˈmɪʃn/', 'sự xả thải các chất gây ô nhiễm', 'Strict clean air regulations mandate dramatic reductions in sulfur pollutant emissions.'),
      w('recycle', 'v', '/ˌriːˈsaɪkl/', 'tái chế phế liệu thành vật phẩm mới', 'Offices are provided with segregated bins to recycle aluminum cans, cardboard, and plastics.'),
      w('ecosystem', 'n', '/ˈiːkəʊsɪstəm/', 'hệ sinh thái tự nhiên', 'Dumping untreated chemical sludge destroys aquatic biodiversity and delicate river ecosystems.'),
      w('drain', 'v', '/dreɪn/', 'làm cạn kiệt nguồn nước/tài nguyên', 'Intensive commercial agriculture threatens to drain underground aquifers dry.'),
      w('hazardous waste', 'n phr', '/ˈhæzədəs weɪst/', 'chất thải nguy hại, độc hại', 'Licensed disposal agencies safely transport hazardous waste to secure incineration facilities.'),
      w('energy-efficient', 'adj', '/ˌenədʒi ɪˈfɪʃnt/', 'tiết kiệm năng lượng tiêu thụ', 'Switching to energy-efficient LED light bulbs dropped corporate electricity spending drastically.'),
      w('carbon neutral', 'adj phr', '/ˌkɑːbən ˈnjuːtrəl/', 'trung hòa carbon (không phát thải ròng)', 'The tech giant committed to making its entire cloud infrastructure carbon neutral by 2030.'),
      w('landfill', 'n', '/ˈlændfɪl/', 'bãi chôn lấp rác thải sinh hoạt', 'Diverting organic food scraps to composting prevents tons of waste from entering landfills.'),
      w('geothermal', 'adj', '/ˌdʒiːəʊˈθɜːml/', 'thuộc địa nhiệt dưới lòng đất', 'Iceland heats over 90% of residential homes using abundant geothermal energy sources.'),
      w('compost', 'v, n', '/ˈkɒmpɒst/', 'ủ rác hữu cơ làm phân bón; phân hữu cơ', 'The corporate cafeteria composts vegetable peelings and coffee grounds for the community garden.'),
      w('hydroelectric', 'adj', '/ˌhaɪdrəʊɪˈlektrɪk/', 'thuộc thủy điện', 'The monumental river dam provides cheap hydroelectric power to five surrounding provinces.'),
      w('afforestation', 'n', '/əˌfɒrɪˈsteɪʃn/', 'hoạt động trồng rừng phủ xanh đất trống', 'The government financed an ambitious afforestation project to halt expanding desertification.'),
      w('habitat', 'n', '/ˈhæbɪtæt/', 'môi trường sống tự nhiên của sinh vật', 'Wetland conservation protects the vital wintering habitat of migratory waterfowl.'),
      w('sustainable', 'adj', '/səˈsteɪnəbl/', 'bền vững, thân thiện với tương lai', 'The timber conglomerate harvests trees from certified sustainable forest plantations.'),
      w('ecological', 'adj', '/ˌiːkəˈlɒdʒɪkl/', 'thuộc về sinh thái học', 'The proposed offshore runway design must pass rigorous ecological impact assessments.'),
      w('drought', 'n', '/draʊt/', 'hạn hán kéo dài thiếu nước', 'Prolonged summer droughts severely lowered reservoir levels and curbed agricultural yields.'),
      w('deforestation', 'n', '/diːˌfɒrɪˈsteɪʃn/', 'nạn phá rừng, chặt phá trơ trọi', 'Satellite imagery tracks illegal deforestation deep inside protected tropical rainforests.'),
      w('fossil fuel', 'n phr', '/ˈfɒsl fjuːəl/', 'nhiên liệu hóa thạch (than đá, dầu mỏ)', 'Subsidies are shifting steadily away from fossil fuels toward zero-emission clean technology.'),
      w('effluent', 'n', '/ˈefluənt/', 'nước thải công nghiệp xả ra', 'Chemical plants must neutralize toxic effluent prior to releasing treated water into the bay.'),
      w('greenhouse gas', 'n phr', '/ˈɡriːnhaʊs ɡæs/', 'khí nhà kính giữ nhiệt khí quyển', 'Methane emissions from animal husbandry represent a potent atmospheric greenhouse gas.'),
      w('biodiversity', 'n', '/ˌbaɪəʊdaɪˈvɜːsəti/', 'sự đa dạng sinh học các loài', 'Preserving coral reefs is vital to maintaining marine biodiversity and coastal fisheries.')
    ]
  },
  {
    id: 27,
    title: 'Quản lý dự án, Lập tiến độ & Phân bổ nguồn lực (Project Management & Deadlines)',
    words: [
      w('deadline', 'n', '/ˈdedlaɪn/', 'hạn chót hoàn thành công việc', 'The engineering squad worked late shifts to meet the strict project deadline.'),
      w('milestone', 'n', '/ˈmaɪlstəʊn/', 'cột mốc quan trọng trong tiến độ', 'Completing the foundation ahead of schedule marked a crucial milestone for the project.'),
      w('allocate', 'v', '/ˈæləkeɪt/', 'phân bổ ngân sách, nhân lực cho dự án', 'The board allocated an additional $2 million to speed up software development.'),
      w('timeline', 'n', '/ˈtaɪmlaɪn/', 'tiến độ thời gian, lịch trình thực hiện', 'The project manager outlined a realistic timeline spanning eight development sprints.'),
      w('deliverable', 'n', '/dɪˈlɪvərəbl/', 'sản phẩm/kết quả bàn giao theo hợp đồng', 'Key project deliverables include system architecture diagrams and working source code.'),
      w('scope', 'n', '/skəʊp/', 'phạm vi quy mô của dự án', 'Any changes to project scope must be formally approved through a change request.'),
      w('feasibility study', 'n phr', '/ˌfiːzəˈbɪləti ˈstʌdi/', 'nghiên cứu tính khả thi của dự án', 'Consultants conducted a feasibility study before greenlighting the bridge construction.'),
      w('contingency plan', 'n phr', '/kənˈtɪndʒənsi plæn/', 'kế hoạch dự phòng khi có sự cố', 'A contingency plan was drafted in case raw material suppliers suffered logistical delays.'),
      w('project sponsor', 'n phr', '/ˈprɒdʒekt ˈspɒnsə(r)/', 'nhà tài trợ/bảo trợ dự án cấp cao', 'The executive project sponsor approved the expanded budget for additional engineers.'),
      w('backlog', 'n', '/ˈbæklɒɡ/', 'công việc tồn đọng cần giải quyết', 'The developer sprint team worked through thirty priority bug fixes from the issue backlog.'),
      w('scrum', 'n', '/skrʌm/', 'phương pháp họp nhanh quản lý dự án Agile', 'The engineering team gathers for a daily 15-minute standing scrum meeting at 9:15.'),
      w('critical path', 'n phr', '/ˈkrɪtɪkl pɑːθ/', 'đường găng (chuỗi nhiệm vụ quyết định tiến độ)', 'Delays on the critical path will inevitably push back the final commercial launch date.'),
      w('roadblock', 'n', '/ˈrəʊdblɒk/', 'vật cản, trở ngại ngáng đường tiến độ', 'Regulatory zoning approvals proved to be the major roadblock for construction.'),
      w('subcontract', 'v, n', '/ˌsʌbkənˈtrækt/', 'giao thầu phụ công việc chuyên môn', 'The general contractor subcontracted electrical wiring to a specialized local firm.'),
      w('overrun', 'n, v', '/ˈəʊvərʌn/', 'vượt quá dự toán ngân sách/thời gian', 'Careful cost tracking prevented budget overruns during the stadium refurbishment.'),
      w('postpone', 'v', '/pəˈspəʊn/', 'trì hoãn lùi lại thời gian thực hiện', 'The committee agreed to postpone the rollout until software stability issues were resolved.'),
      w('accelerate', 'v', '/əkˈseləreɪt/', 'đẩy nhanh tiến độ thi công', 'Hiring extra field contractors helped accelerate completion of the rail line by two weeks.'),
      w('key performance indicator', 'n phr', '/kiː pəˈfɔːməns ˈɪndɪkeɪtə(r)/', 'chỉ số đo lường hiệu quả công việc (KPI)', 'Hitting project milestones is our team’s primary key performance indicator.'),
      w('resource allocation', 'n phr', '/rɪˈzɔːs ˌæləˈkeɪʃn/', 'sự phân bổ và tận dụng nguồn lực', 'Efficient resource allocation ensures no single engineer is burdened with excessive overtime.'),
      w('gantt chart', 'n phr', '/ɡænt tʃɑːt/', 'biểu đồ tiến độ Gantt trực quan', 'The project lead displayed a Gantt chart visualizing overlapping project phases.'),
      w('sign-off', 'n', '/ˈsaɪn ɒf/', 'sự phê duyệt chính thức bằng chữ ký', 'We cannot proceed to production without formal executive sign-off on the blueprints.'),
      w('kick-off meeting', 'n phr', '/ˈkɪk ɒf ˈmiːtɪŋ/', 'cuộc họp khởi động dự án mới', 'The client and development squads aligned on key priorities during the project kick-off meeting.'),
      w('system requirements', 'n phr', '/ˈsɪstəm rɪˈkwaɪəmənts/', 'yêu cầu kỹ thuật phần mềm cần đáp ứng', 'The software architecture document outlines all mandatory system requirements.'),
      w('status report', 'n phr', '/ˈsteɪtəs rɪˈpɔːt/', 'báo cáo cập nhật tiến độ công việc', 'Every Friday afternoon, team captains submit a written status report to the VP of operations.'),
      w('dependency', 'n', '/dɪˈpendənsi/', 'sự phụ thuộc giữa các công đoạn', 'Database schema migration is a prerequisite dependency for API deployment.'),
      w('sub-assign', 'v', '/sʌb əˈsaɪn/', 'phân công giao việc thứ cấp cho tổ đội', 'Team captains sub-assign smaller programming tickets to junior developers.'),
      w('streamline', 'v', '/ˈstriːmlaɪn/', 'tinh gọn hóa quy trình làm việc', 'Automating build pipelines streamlined software releases from days down to minutes.'),
      w('turnaround', 'n', '/ˈtɜːnəraʊnd/', 'thời gian hoàn tất một nhiệm vụ', 'Our creative agency is renowned for rapid turnaround times on urgent ad copy.'),
      w('oversight', 'n', '/ˈəʊvəsaɪt/', 'sự giám sát chỉ đạo; sơ suất bỏ quên', 'The oversight committee monitors high-risk expenditures to prevent embezzlement.'),
      w('deliver', 'v', '/dɪˈlɪvə(r)/', 'hoàn thành và bàn giao sản phẩm đúng hẹn', 'The team worked relentlessly to deliver the mobile banking platform before Q4.')
    ]
  },
  {
    id: 28,
    title: 'Bẫy liên từ, Trạng từ liên kết & Giới từ Part 5, 6 (Grammar Traps)',
    words: [
      w('notwithstanding', 'prep', '/ˌnɒtwɪθˈstændɪŋ/', 'mặc dù, bất kể (= despite / in spite of)', 'Notwithstanding severe supply shortages, the manufacturing team hit its quarterly quota.'),
      w('furthermore', 'adv', '/ˌfɜːðəˈmɔː(r)/', 'hơn nữa, vả lại (= in addition / moreover)', 'The system is cost-effective; furthermore, it requires minimal ongoing maintenance.'),
      w('consequently', 'adv', '/ˈkɒnsɪkwəntli/', 'do đó, hệ quả là (= as a result / therefore)', 'Consumer demand plunged; consequently, retail inventory sat unpurchased on warehouse shelves.'),
      w('nevertheless', 'adv', '/ˌnevəðəˈles/', 'tuy nhiên, dù vậy (= however / nonetheless)', 'Economic forecasts look gloomy; nevertheless, the firm plans to expand its regional branches.'),
      w('whereas', 'conj', '/ˌweərˈæz/', 'trong khi đó (chỉ sự đối lập tương phản)', 'Online sales skyrocketed by 40%, whereas foot traffic at brick-and-mortar stores fell.'),
      w('provided that', 'conj phr', '/prəˈvaɪdɪd ðæt/', 'miễn là, với điều kiện là (= only if / as long as)', 'You may take Friday off provided that all your urgent project tasks are completed.'),
      w('in the event of', 'prep phr', '/ɪn ði ɪˈvent əv/', 'trong trường hợp xảy ra việc gì (= in case of)', 'In the event of a fire alarm, immediately evacuate via the nearest illuminated stairwell.'),
      w('given that', 'conj phr', '/ˈɡɪvn ðæt/', 'xét đến việc, căn cứ vào việc (= considering that)', 'Given that raw material costs have doubled, a price increase on finished goods is inevitable.'),
      w('on behalf of', 'prep phr', '/ɒn bɪˈhɑːf əv/', 'thay mặt cho, đại diện cho ai', 'On behalf of the board of directors, I would like to welcome our esteemed keynote guests.'),
      w('in light of', 'prep phr', '/ɪn laɪt əv/', 'bởi vì, căn cứ theo tình hình (= because of)', 'In light of recent budget constraints, all non-essential business travel is canceled.'),
      w('regardless of', 'prep phr', '/rɪˈɡɑːdləs əv/', 'bất kể, không màng tới (= irrespective of)', 'All eligible staff may apply for the fellowship regardless of length of tenure.'),
      w('subsequent to', 'prep phr', '/ˈsʌbsɪkwənt tuː/', 'sau khi, tiếp sau sự việc (= following / after)', 'Subsequent to the board meeting, an official corporate memorandum was circulated.'),
      w('prior to', 'prep phr', '/ˈpraɪə tuː/', 'trước khi (= before)', 'All visitors must present valid photo identification prior to entering the server facility.'),
      w('in accordance with', 'prep phr', '/ɪn əˈkɔːdns wɪð/', 'phù hợp với, tuân theo quy định', 'Annual financial audits must be performed in accordance with federal accounting guidelines.'),
      w('as opposed to', 'prep phr', '/æz əˈpəʊzd tuː/', 'thay vì, đối lập hẳn với', 'We selected a cloud solution as opposed to constructing an expensive on-premise datacenter.'),
      w('in addition to', 'prep phr', '/ɪn əˈdɪʃn tuː/', 'bên cạnh, ngoài ra còn (= besides / aside from)', 'In addition to competitive base wages, the job offer includes comprehensive healthcare perks.'),
      w('owing to', 'prep phr', '/ˈəʊɪŋ tuː/', 'nhờ vào, do vì (= due to / because of)', 'Flight cancellations were widespread owing to severe zero-visibility blizzard conditions.'),
      w('in spite of', 'prep phr', '/ɪn spaɪt əv/', 'mặc dù, bất chấp (= despite)', 'In spite of fierce market competition, the tech startup captured a 15% domestic market share.'),
      w('meanwhile', 'adv', '/ˈmiːnwaɪl/', 'trong lúc đó, trong khi chờ đợi', 'The CEO addressed foreign journalists; meanwhile, technicians tested the demo equipment.'),
      w('hence', 'adv', '/hens/', 'do đó, vì lý do ấy (= therefore)', 'The merger creates unmatched synergies, hence our supreme confidence in next year’s revenue.'),
      w('likewise', 'adv', '/ˈlaɪkwaɪz/', 'tương tự như vậy, cũng thế (= similarly)', 'Our European branch reported soaring revenues, and domestic operations performed likewise.'),
      w('inasmuch as', 'conj', '/ˌɪnəzˈmʌtʃ æz/', 'bởi vì, xét thấy rằng (= since / seeing that)', 'Inasmuch as the tenant breached the lease covenant, the landlord commenced eviction proceedings.'),
      w('concerning', 'prep', '/kənˈsɜːnɪŋ/', 'liên quan tới, về vấn đề (= regarding / about)', 'Call human resources if you have questions concerning the updated healthcare benefits.'),
      w('pertaining to', 'prep phr', '/pəˈteɪnɪŋ tuː/', 'thuộc về, liên quan mật thiết tới', 'Documents pertaining to the corporate acquisition were locked inside the legal vault.'),
      w('except for', 'prep phr', '/ɪkˈsept fɔː(r)/', 'ngoại trừ, trừ trường hợp', 'The executive offices are closed on weekends except for authorized security personnel.'),
      w('unless', 'conj', '/ənˈles/', 'trừ khi, nếu không (= if not)', 'Contracts cannot be signed unless both parties have reviewed the finalized clause addenda.'),
      w('so that', 'conj', '/səʊ ðæt/', 'để mà (chỉ mục đích hành động)', 'Please speak clearly into the microphone so that delegates in the gallery can hear.'),
      w('as though', 'conj', '/æz ðəʊ/', 'như thể là (= as if)', 'The stock market rallied strongly as though interest rates had already been slashed.'),
      w('with respect to', 'prep phr', '/wɪð rɪˈspekt tuː/', 'đối với, liên quan đến vấn đề gì', 'The committee expressed satisfaction with respect to our environmental compliance progress.'),
      w('in contrast to', 'prep phr', '/ɪn ˈkɒntrɑːst tuː/', 'trái ngược hoàn toàn với', 'In contrast to last quarter’s massive losses, our Q3 operating margins improved remarkably.')
    ]
  },
  {
    id: 29,
    title: 'Các cặp từ bẫy dễ gây nhầm lẫn kinh điển Part 5 (Confusing Word Pairs)',
    words: [
      w('economic', 'adj', '/ˌiːkəˈnɒmɪk/', 'thuộc về nền kinh tế quốc gia', 'The central bank introduced fiscal policies to stimulate national economic growth.'),
      w('economical', 'adj', '/ˌiːkəˈnɒmɪkl/', 'tiết kiệm tiền bạc, tiết kiệm nhiên liệu', 'Hybrid sedans are far more economical to run than gas-guzzling sport utility vehicles.'),
      w('considerable', 'adj', '/kənˈsɪdərəbl/', 'đáng kể, to lớn về số lượng/quy mô', 'The restructuring plan saved the company a considerable amount of operational capital.'),
      w('considerate', 'adj', '/kənˈsɪdərət/', 'chu đáo, biết ân cần quan tâm người khác', 'It was very considerate of the department head to order lunch for the overtime crew.'),
      w('sensible', 'adj', '/ˈsensəbl/', 'hợp lý, biết điều, có óc phán đoán', 'Investing a portion of your savings in diversified index funds is a very sensible strategy.'),
      w('sensitive', 'adj', '/ˈsensətɪv/', 'nhạy cảm, cơ mật (dữ liệu, thông tin)', 'The legal memo contains highly sensitive information regarding the pending intellectual patent.'),
      w('successive', 'adj', '/səkˈsesɪv/', 'liên tiếp nhau không gián đoạn (= consecutive)', 'The retail conglomerate posted record profits for four successive fiscal quarters.'),
      w('successful', 'adj', '/səkˈsesfl/', 'thành công, đạt kết quả tốt đẹp', 'The marketing campaign was extraordinarily successful in attracting younger demographics.'),
      w('comprehensible', 'adj', '/ˌkɒmprɪˈhensəbl/', 'có thể hiểu được, dễ hiểu', 'The user manual translates complex technical jargon into easily comprehensible steps.'),
      w('comprehensive', 'adj', '/ˌkɒmprɪˈhensɪv/', 'toàn diện, bao quát mọi mặt', 'The consultant prepared a comprehensive audit covering human resources and finance.'),
      w('confident', 'adj', '/ˈkɒnfɪdənt/', 'tự tin, tin tưởng chắc chắn', 'The sales team is confident that they will hit their annual revenue milestone.'),
      w('confidential', 'adj', '/ˌkɒnfɪˈdenʃl/', 'bảo mật, tuyệt mật không tiết lộ', 'All medical records and patient health files are maintained under confidential cover.'),
      w('respectable', 'adj', '/rɪˈspektəbl/', 'đáng kính trọng, đứng đắn, khá tốt', 'The junior analyst earned a respectable quarterly performance bonus in her first year.'),
      w('respectful', 'adj', '/rɪˈspektfl/', 'tôn trọng, cung kính lễ phép', 'Employees are expected to remain professional and respectful toward dissatisfied clients.'),
      w('respective', 'adj', '/rɪˈspektɪv/', 'tương ứng của từng người/vật', 'After the joint plenary session, delegates returned to their respective breakout rooms.'),
      w('industrial', 'adj', '/ɪnˈdʌstriəl/', 'thuộc về ngành công nghiệp, nhà máy', 'The city zoned the northern waterfront district specifically for industrial manufacturing.'),
      w('industrious', 'adj', '/ɪnˈdʌstriəs/', 'cần cù, chăm chỉ siêng năng (= hard-working)', 'The industrious intern completed her data entry assignments hours ahead of the deadline.'),
      w('historic', 'adj', '/hɪˈstɒrɪk/', 'mang tính lịch sử, mang ý nghĩa trọng đại', 'Signing the transatlantic trade treaty was widely hailed as a historic milestone.'),
      w('historical', 'adj', '/hɪˈstɒrɪkl/', 'thuộc về quá khứ lịch sử, có thật trong sử', 'The research analysts scrutinized historical stock price volatility over the past five decades.'),
      w('beneficial', 'adj', '/ˌbenɪˈfɪʃl/', 'có lợi, mang lại lợi ích', 'Regular software training is enormously beneficial for long-term employee productivity.'),
      w('beneficent', 'adj', '/bɪˈnefɪsnt/', 'hay làm việc từ thiện, nhân từ bác ái', 'The corporation’s beneficent founder endowed multiple academic university scholarships.'),
      w('comparable', 'adj', '/ˈkɒmpərəbl/', 'tương đương, có thể so sánh ngang hàng', 'Our product offers performance comparable to market leaders at half the retail price.'),
      w('comparative', 'adj', '/kəmˈpærətɪv/', 'so sánh tương đối, dựa trên đối chiếu', 'The research department conducted a comparative pricing analysis across five rival stores.'),
      w('exhausting', 'adj', '/ɪɡˈzɔːstɪŋ/', 'làm kiệt sức, gây mệt mỏi rã rời', 'Preparing the annual shareholder prospectus was an exhausting month-long ordeal.'),
      w('exhaustive', 'adj', '/ɪɡˈzɔːstɪv/', 'toàn diện, thấu đáo không bỏ sót chi tiết', 'Forensic accountants carried out an exhaustive investigation of the missing inventory logs.'),
      w('faultless', 'adj', '/ˈfɔːltləs/', 'hoàn hảo không tì vết (= flawless)', 'The pianist delivered a faultless performance at the corporate charity symphony.'),
      w('faulty', 'adj', '/ˈfɔːlti/', 'bị lỗi kỹ thuật, hỏng hóc', 'The automaker recalled 10,000 sedans to replace faulty electrical wiring harnesses.'),
      w('priceless', 'adj', '/ˈpraɪsləs/', 'vô giá, cực kỳ quý giá (= invaluable)', 'Her decades of corporate restructuring experience proved priceless during the hostile takeover.'),
      w('worthless', 'adj', '/ˈwɜːθləs/', 'vô giá trị, không có một xu giá trị', 'Counterfeit stock certificates are entirely worthless on legitimate global exchanges.'),
      w('invaluable', 'adj', '/ɪnˈvæljuəbl/', 'vô cùng quý báu, không thể định giá được', 'The mentor’s strategic advice was invaluable in guiding the fledgling startup to profitability.')
    ]
  },
  {
    id: 30,
    title: 'Cụm từ cố định & Đi kèm bắt buộc Part 5, 6 (Business Collocations)',
    words: [
      w('meet the deadline', 'coll', '/miːt ðə ˈdedlaɪn/', 'kịp thời hạn chót', 'Engineers put in extra weekend hours to ensure the project met its strict deadline.'),
      w('conduct a survey', 'coll', '/kənˈdʌkt ə ˈsɜːveɪ/', 'tiến hành khảo sát lấy ý kiến', 'The marketing agency conducted an online survey of over 2,000 suburban households.'),
      w('broaden the market', 'coll', '/ˈbrɔːdn ðə ˈmɑːkɪt/', 'mở rộng thị trường tiêu thụ', 'Launching an affordable product line helped broaden the market across emerging nations.'),
      w('fulfill the criteria', 'coll', '/fʊlˈfɪl ðə kraɪˈtɪəriə/', 'đáp ứng đầy đủ tiêu chí đề ra', 'Only two candidates fulfilled all the strict criteria outlined in the job description.'),
      w('reach an agreement', 'coll', '/riːtʃ ən əˈɡriːmənt/', 'đạt được thỏa thuận chung', 'After twelve hours of negotiation, union leaders and management finally reached an agreement.'),
      w('raise objections', 'coll', '/reɪz əbˈdʒekʃnz/', 'nêu ý kiến phản đối/bác bỏ', 'Several board members raised sharp objections to the CEO’s proposed executive salary hike.'),
      w('implement a policy', 'coll', '/ˈɪmplɪment ə ˈpɒləsi/', 'áp dụng, ban hành chính sách mới', 'The hospital implemented a strict zero-tolerance sanitation policy in all operating theaters.'),
      w('exercise caution', 'coll', '/ˈeksəsaɪz ˈkɔːʃn/', 'thận trọng, cẩn thận đề phòng', 'Financial advisors urge individual investors to exercise caution during volatile markets.'),
      w('exceed expectations', 'coll', '/ɪkˈsiːd ˌekspekˈteɪʃnz/', 'vượt quá sự kỳ vọng ban đầu', 'Quarterly earnings exceeded Wall Street expectations by nearly fifteen percentage points.'),
      w('draw up a contract', 'coll', '/drɔː ʌp ə ˈkɒntrækt/', 'soạn thảo văn bản hợp đồng', 'Corporate attorneys met behind closed doors to draw up a commercial partnership contract.'),
      w('express concern', 'coll', '/ɪkˈspres kənˈsɜːn/', 'bày tỏ sự quan ngại lo lắng', 'Environmental activists expressed concern over chemical runoff into the local reservoir.'),
      w('take into account', 'coll', '/teɪk ˈɪntuː əˈkaʊnt/', 'tính đến, xem xét cân nhắc kỹ', 'Engineers must take harsh winter temperatures into account when designing bridge cables.'),
      w('launch a campaign', 'coll', '/lɔːntʃ ə kæmˈpeɪn/', 'tung ra chiến dịch quảng bá', 'The company launched an aggressive digital campaign to announce the holiday sales discounts.'),
      w('address the issue', 'coll', '/əˈdres ði ˈɪʃuː/', 'giải quyết vấn đề tồn đọng', 'Management held an all-hands assembly to address the issue of employee burnout and fatigue.'),
      w('make a reservation', 'coll', '/meɪk ə ˌrezəˈveɪʃn/', 'tiến hành đặt chỗ trước', 'You must make a reservation online if you intend to dine in the panoramic rooftop lounge.'),
      w('give a presentation', 'coll', '/ɡɪv ə ˌpreznˈteɪʃn/', 'thuyết trình, trình bày báo cáo', 'The Chief Financial Officer will give a comprehensive presentation on Q3 profits today.'),
      w('gain market share', 'coll', '/ɡeɪn ˈmɑːkɪt ʃeə(r)/', 'giành thêm thị phần tiêu thụ', 'Competitive pricing allowed the electric vehicle maker to gain substantial market share.'),
      w('file a complaint', 'coll', '/faɪl ə kəmˈpleɪnt/', 'nộp đơn khiếu nại chính thức', 'Passengers filed a joint complaint with the aviation authority over the 24-hour stranding.'),
      w('pay in installments', 'coll', '/peɪ ɪn ɪnˈstɔːlmənts/', 'thanh toán theo hình thức trả góp', 'Customers can pay in twelve equal monthly installments with zero added interest charges.'),
      w('bear the responsibility', 'coll', '/beə ðə rɪˌspɒnsəˈbɪləti/', 'chịu trách nhiệm về hậu quả', 'The project manager accepted to bear the ultimate responsibility for the software delay.'),
      w('pose a threat', 'coll', '/pəʊz ə θret/', 'gây ra mối đe dọa, hiểm họa', 'Counterfeit microchips pose a severe threat to the reliability of aerospace navigation systems.'),
      w('incur expenses', 'coll', '/ɪnˈkɜːr ɪkˈspensɪz/', 'phát sinh chi phí trong quá trình làm', 'Employees will be reimbursed for any travel expenses incurred during official company trips.'),
      w('reach a consensus', 'coll', '/riːtʃ ə kənˈsensəs/', 'đạt được sự đồng thuận nhất trí', 'The selection committee reached a unanimous consensus regarding the new creative director.'),
      w('place an order', 'coll', '/pleɪs ən ˈɔːdə(r)/', 'tiến hành đặt một đơn hàng', 'Clients who place an order of over $500 qualify for free express courier shipping.'),
      w('play a pivotal role', 'coll', '/pleɪ ə ˈpɪvətl rəʊl/', 'đóng vai trò then chốt cốt tử', 'Advanced data analytics played a pivotal role in optimizing logistics delivery routes.'),
      w('undergo an inspection', 'coll', '/ˌʌndəˈɡəʊ ən ɪnˈspekʃn/', 'trải qua đợt thanh tra giám định', 'The pharmaceutical compounding lab must undergo an annual health and safety inspection.'),
      w('hold a press conference', 'coll', '/həʊld ə pres ˈkɒnfərəns/', 'tổ chức một buổi họp báo chí', 'Executives held a televised press conference to announce the appointment of the new CEO.'),
      w('fall short of expectations', 'coll', '/fɔːl ʃɔːt əv ˌekspekˈteɪʃnz/', 'không đạt được như kỳ vọng', 'Sales figures for the new tablet fell short of Wall Street expectations by 12 percent.'),
      w('strike a balance', 'coll', '/straɪk ə ˈbæləns/', 'tạo sự cân bằng hài hòa giữa hai bên', 'Leadership must strike a balance between aggressive business growth and employee well-being.'),
      w('have reservations about', 'coll', '/hæv ˌrezəˈveɪʃnz əˈbaʊt/', 'có sự e dè, hoài nghi chưa yên tâm', 'Several senior partners had serious reservations about acquiring the unprofitable competitor.')
    ]
  },
  {
    id: 31,
    title: 'Trạng từ mức độ & Bổ ngữ bẫy điểm cao Part 5, 6 (High-Score Modifiers)',
    words: [
      w('substantially', 'adv', '/səbˈstænʃəli/', 'đáng kể, rất nhiều (= significantly / considerably)', 'Operating profits increased substantially following the automation of the factory.'),
      w('drastically', 'adv', '/ˈdræstɪkli/', 'mạnh mẽ, quyết liệt, trầm trọng', 'The airline drastically reduced international flight schedules during the volcanic eruption.'),
      w('dramatically', 'adv', '/drəˈmætɪkli/', 'đột ngột, ngoạn mục, rõ rệt', 'Customer churn fell dramatically once the 24/7 technical hotline was introduced.'),
      w('consistently', 'adv', '/kənˈsɪstəntli/', 'nhất quán, luôn luôn ổn định qua thời gian', 'The boutique hotel consistently earns five-star guest reviews on travel websites.'),
      w('readily', 'adv', '/ˈredɪli/', 'sẵn sàng, dễ dàng không chút trở ngại', 'Customer service representatives readily answered technical questions regarding the app.'),
      w('expeditiously', 'adv', '/ˌekspəˈdɪʃəsli/', 'nhanh chóng và hiệu quả vượt bậc', 'The claims department processed insurance payouts expeditiously within 48 hours.'),
      w('meticulously', 'adv', '/məˈtɪkjələsli/', 'tỉ mỉ cẩn thận từng li từng tí', 'The legal team meticulously reviewed every single clause before finalizing the settlement.'),
      w('marginally', 'adv', '/ˈmɑːdʒɪnəli/', 'chỉ một chút, không đáng kể (= slightly)', 'Third-quarter revenues were only marginally higher than the preceding fiscal period.'),
      w('predominantly', 'adv', '/prɪˈdɒmɪnəntli/', 'chủ yếu là, phần lớn là (= mainly / largely)', 'The conference audience was comprised predominantly of senior biotechnology executives.'),
      w('adversely', 'adv', '/ˈædvɜːsli/', 'bất lợi, tiêu cực, có hại', 'Global supply chain bottlenecks adversely affected automotive production schedules.'),
      w('inadvertently', 'adv', '/ˌɪnədˈvɜːtəntli/', 'vô tình, sơ suất không cố ý', 'The clerk inadvertently sent internal pricing matrices to an external client email.'),
      w('unanimously', 'adv', '/juˈnænɪməsli/', 'nhất trí, toàn thể tán thành 100%', 'The board unanimously selected Ms. Jenkins as the new executive vice president.'),
      w('virtually', 'adv', '/ˈvɜːtʃuəli/', 'hầu như, gần như hoàn toàn (= almost)', 'Traditional paper document storage has become virtually obsolete in our digital office.'),
      w('barely', 'adv', '/ˈbeəli/', 'vừa đủ, suýt chút nữa là không (= hardly)', 'We barely caught our connecting flight in Frankfurt due to de-icing runway delays.'),
      w('strictly', 'adv', '/ˈstrɪktli/', 'một cách nghiêm ngặt, tuyệt đối', 'Smoking and vaping are strictly prohibited throughout all corporate premises.'),
      w('remarkably', 'adv', '/rɪˈmɑːkəbli/', 'đáng chú ý, một cách xuất sắc khác thường', 'The prototype battery remained remarkably cool even under heavy computational load.'),
      w('mutually', 'adv', '/ˈmjuːtʃuəli/', 'lẫn nhau, hai bên cùng có lợi', 'Both negotiating firms agreed to work toward a mutually beneficial licensing contract.'),
      w('customarily', 'adv', '/ˈkʌstəmərəli/', 'theo thông lệ thường làm (= usually)', 'Annual corporate bonuses are customarily disbursed on the final banking day of December.'),
      w('exceptionally', 'adv', '/ɪkˈsepʃənəli/', 'đặc biệt xuất sắc, hiếm có', 'The restaurant received exceptionally high marks for its wine pairings and guest service.'),
      w('periodically', 'adv', '/ˌpɪəriˈɒdɪkli/', 'định kỳ, theo chu kỳ đều đặn', 'IT specialists periodically update security certificates to prevent hacking attacks.'),
      w('moderately', 'adv', '/ˈmɒdərətli/', 'ở mức vừa phải, trung bình', 'Economic forecasters predict only moderately higher consumer spending this holiday season.'),
      w('sparingly', 'adv', '/ˈspeərɪŋli/', 'một cách dè sẻn, tiết kiệm ít dùng', 'Use intense chemical cleaning solvents sparingly to avoid damaging delicate marble counters.'),
      w('tentatively', 'adv', '/ˈtentətɪvli/', 'tạm thời, chưa chốt dứt khoát', 'The executive product launch has been tentatively scheduled for early November.'),
      w('unconditionally', 'adv', '/ˌʌnkənˈdɪʃənəli/', 'vô điều kiện, hoàn toàn tuyệt đối', 'The premium manufacturer unconditionally guarantees replacement for any defective parts.'),
      w('reluctantly', 'adv', '/rɪˈlʌktəntli/', 'miễn cưỡng, không đành lòng', 'The board reluctantly accepted the founding CEO’s request for immediate retirement.'),
      w('subsequently', 'adv', '/ˈsʌbsɪkwəntli/', 'sau đó, tiếp sau đó (= afterwards)', 'The company restructured operations and subsequently reported robust quarterly profits.'),
      w('adequately', 'adv', '/ˈædɪkwətli/', 'đầy đủ, thỏa đáng đáp ứng yêu cầu', 'Ensure all factory assembly workers are adequately trained on hazardous emergency stop switches.'),
      w('deliberately', 'adv', '/dɪˈlɪbərətli/', 'cố ý, có chủ đích tính toán trước', 'The design team deliberately omitted the headphone jack to ensure complete waterproofing.'),
      w('routinely', 'adv', '/ruːˈtiːnli/', 'theo thói quen thường lệ hằng ngày', 'The safety officer routinely inspects fire extinguishers on the first Monday of each month.'),
      w('profoundly', 'adv', '/prəˈfaʊndli/', 'sâu sắc, tác động vô cùng to lớn', 'The sudden adoption of generative artificial intelligence profoundly transformed corporate workflows.')
    ]
  },
  {
    id: 32,
    title: 'Động từ trang trọng & Học thuật Part 7 (Formal Business Verbs)',
    words: [
      w('earmark', 'v', '/ˈɪəmɑːk/', 'dành riêng một khoản ngân sách cho mục đích gì', 'The city council earmarked $10 million for upgrading public commuter stations.'),
      w('commence', 'v', '/kəˈmens/', 'bắt đầu, khởi sự (= begin / start)', 'Demolition work on the abandoned warehouse will commence next Monday.'),
      w('designate', 'v', '/ˈdezɪɡneɪt/', 'chỉ định, bổ nhiệm vào vị trí trọng trách', 'Mr. Alvarez was designated as the official team leader for the merger audit.'),
      w('divulge', 'v', '/daɪˈvʌldʒ/', 'tiết lộ, công khai thông tin bí mật', 'Corporations are strictly forbidden to divulge proprietary client algorithms.'),
      w('relinquish', 'v', '/rɪˈlɪŋkwɪʃ/', 'từ bỏ, nhượng lại quyền lực/quyền sở hữu', 'The aging founder agreed to relinquish his controlling interest in the conglomerate.'),
      w('supplement', 'v', '/ˈsʌplɪment/', 'bổ sung, gia tăng thêm vào cái có sẵn', 'Many freelancers take on consulting projects to supplement their primary income.'),
      w('undergo', 'v', '/ˌʌndəˈɡəʊ/', 'trải qua (quy trình, kiểm tra, phẫu thuật)', 'All incoming cargo must undergo rigorous x-ray screening at border checkpoints.'),
      w('utilize', 'v', '/ˈjuːtəlaɪz/', 'tận dụng, sử dụng hiệu quả (= make use of)', 'The marketing agency utilizes advanced analytics to optimize conversion funnels.'),
      w('withstand', 'v', '/wɪðˈstænd/', 'chịu đựng được, chống chọi được áp lực', 'The new offshore wind turbines are engineered to withstand Category 5 hurricanes.'),
      w('ascertain', 'v', '/ˌæsəˈteɪn/', 'xác minh, tìm hiểu sự thật chắc chắn', 'Auditors conducted interviews to ascertain the origin of the accounting discrepancy.'),
      w('elaborate', 'v', '/ɪˈlæbəreɪt/', 'giải thích tỉ mỉ chi tiết hơn', 'The director was asked to elaborate on his proposal during the Q&A session.'),
      w('reinstate', 'v', '/ˌriːɪnˈsteɪt/', 'phục hồi chức vụ, tái lập chính sách', 'Management agreed to reinstate the employee discount program starting next week.'),
      w('facilitate', 'v', '/fəˈsɪlɪteɪt/', 'tạo điều kiện thuận lợi, làm cho dễ dàng', 'Modern project management software facilitates seamless communication across distributed teams.'),
      w('consolidate', 'v', '/kənˈsɒlɪdeɪt/', 'hợp nhất lại, củng cố vị thế vững mạnh', 'The bank consolidated its regional branch network to eliminate redundant overhead.'),
      w('prescribe', 'v', '/prɪˈskraɪb/', 'quy định cụ thể quy tắc/biện pháp thi hành', 'Federal guidelines prescribe mandatory daily safety inspections for commercial aircraft.'),
      w('curtail', 'v', '/kɜːˈteɪl/', 'cắt giảm bớt, hạn chế (chi phí, hoạt động)', 'The company curtailed international travel expenses in response to slumping Q2 profits.'),
      w('quicken', 'v', '/ˈkwɪkən/', 'làm nhanh thêm, đẩy nhanh tiến trình', 'Automation and modular components helped quicken the tempo of chassis assembly.'),
      w('disseminate', 'v', '/dɪˈsemɪneɪt/', 'phổ biến, truyền bá thông tin rộng rãi', 'Human resources will disseminate the revised corporate conduct handbook by email.'),
      w('jeopardize', 'v', '/ˈdʒepədaɪz/', 'gây nguy hiểm, liều lĩnh đe dọa sự an toàn', 'Failing to meet client data security standards could jeopardize the entire contract.'),
      w('ratify', 'v', '/ˈrætɪfaɪ/', 'phê chuẩn chính thức (hiệp định, điều ước)', 'The union members voted by a 70% majority to ratify the new three-year labor pact.'),
      w('substantiate', 'v', '/səbˈstænʃieɪt/', 'chứng minh bằng bằng chứng xác thực', 'The claimant failed to substantiate her damage claims with itemized purchase receipts.'),
      w('peruse', 'v', '/pəˈruːz/', 'đọc kỹ lưỡng, xem xét cẩn thận từng chữ', 'Please peruse the contract provisions thoroughly before signing on the dotted line.'),
      w('supersede', 'v', '/ˌsuːpəˈsiːd/', 'thay thế cái cũ, chiếm chỗ (= replace)', 'The updated 2026 corporate safety guidelines supersede all previously issued manuals.'),
      w('authorize', 'v', '/ˈɔːθəraɪz/', 'ủy quyền, cho phép chính thức bằng văn bản', 'Only the Chief Financial Officer is authorized to approve capital purchases over $50,000.'),
      w('reaffirm', 'v', '/ˌriːəˈfɜːm/', 'tái khẳng định cam kết/chính sách', 'The chairman reaffirmed the corporation’s goal of achieving net-zero carbon operations.'),
      w('deter', 'v', '/dɪˈtɜː(r)/', 'ngăn cản, làm nản lòng không dám làm', 'High penalty clauses are designed to deter suppliers from violating delivery schedules.'),
      w('alleviate', 'v', '/əˈliːvieɪt/', 'làm dịu bớt, giảm nhẹ nỗi đau/tình trạng', 'Widening the commuter highway helped alleviate chronic rush-hour traffic gridlock.'),
      w('harmonize', 'v', '/ˈhɑːmənaɪz/', 'hài hòa hóa các quy chuẩn/số liệu khác biệt', 'Cross-border regulators strive to harmonize pharmaceutical testing standards.'),
      w('culminate', 'v', '/ˈkʌlmɪneɪt/', 'lên đến đỉnh điểm, kết thúc bằng kết quả', 'Months of tense negotiations culminated in a historic multi-billion-dollar aerospace merger.'),
      w('mitigate', 'v', '/ˈmɪtɪɡeɪt/', 'giảm nhẹ, làm dịu bớt rủi ro/thiệt hại', 'Hedging strategies helped the export firm mitigate currency fluctuation risks.')
    ]
  },
  {
    id: 33,
    title: 'Bẫy chuyển ngữ & Từ đồng nghĩa nâng cao Part 7 (Paraphrasing Traps)',
    words: [
      w('refurbishment', 'n', '/ˌriːˈfɜːbɪʃmənt/', 'sự tân trang làm mới cơ sở (= remodeling / renovation)', 'The downtown hotel reopened after an extensive twenty-million-dollar refurbishment.'),
      w('apparel', 'n', '/əˈpærəl/', 'trang phục quần áo may mặc (= clothing / attire)', 'The boutique retailer specializes in high-end business apparel for women.'),
      w('patronage', 'n', '/ˈpætrənɪdʒ/', 'sự lui tới ủng hộ của khách quen (= support)', 'We sincerely thank you for your ongoing patronage of our family-owned bookstore.'),
      w('hasten', 'v', '/ˈheɪsn/', 'làm cho nhanh hơn, thúc đẩy (= expedite / rush)', 'Innovative logistics software hastened parcel handling at regional sorting hubs.'),
      w('convenience', 'n', '/kənˈviːniəns/', 'tiện nghi thuận tiện cho đời sống (= amenity)', 'The suburban condo complex offers conveniences such as covered parking and a gym.'),
      w('prospective', 'adj', '/prəˈspektɪv/', 'tiềm năng, triển vọng tương lai (= potential)', 'The sales representative pitched the software demo to prospective corporate clients.'),
      w('inaugurate', 'v', '/ɪˈnɔːɡjəreɪt/', 'khai mạc, khánh thành mở màn (= open / start)', 'The mayor will inaugurate the new international technology park on Monday.'),
      w('remit', 'v', '/rɪˈmɪt/', 'chuyển tiền hoàn trả (= send money / pay / reimburse)', 'The client agreed to remit the outstanding invoice balance via electronic wire.'),
      w('delicate', 'adj', '/ˈdelɪkət/', 'mỏng manh, dễ vỡ hư hại (= sensitive / fragile)', 'Handle delicate optical measuring sensors with utmost caution during transit.'),
      w('complimentary', 'adj', '/ˌkɒmplɪˈmentri/', 'miễn phí kèm theo dịch vụ (= free of charge)', 'The airline provides complimentary beverage service on all domestic flights.'),
      w('inquire', 'v', '/ɪnˈkwaɪə(r)/', 'hỏi thăm, thắc mắc thông tin (= ask / request info)', 'Prospective tenants called the property leasing office to inquire about vacant lofts.'),
      w('in lieu of', 'prep phr', '/ɪn ljuː əv/', 'thay cho, thay thế vào vị trí (= instead of)', 'The award winner received corporate stock options in lieu of a cash bonus.'),
      w('timetable', 'n', '/ˈtaɪmteɪbl/', 'thời gian biểu lịch trình (= schedule / itinerary)', 'The updated train timetable reflects expanded commuter service during peak hours.'),
      w('merchant', 'n', '/ˈmɜːtʃənt/', 'thương gia, người bán hàng (= seller / vendor)', 'Online merchants must comply with secure payment gateway cryptography standards.'),
      w('fluctuate', 'v', '/ˈflʌktʃueɪt/', 'dao động lên xuống thất thường (= vary / oscillate)', 'Gasoline prices fluctuate wildly depending on crude oil market volatility.'),
      w('mandatory', 'adj', '/ˈmændətəri/', 'bắt buộc theo quy định (= compulsory / obligatory)', 'Attendance at the annual corporate cybersecurity training module is strictly mandatory.'),
      w('reposition', 'v', '/ˌriːpəˈzɪʃn/', 'chuyển dời vị trí, tái định vị (= move / relocate)', 'The retail chain will reposition its regional flagship store to the central boulevard.'),
      w('adjacent to', 'prep phr', '/əˈdʒeɪsnt tuː/', 'ngay kế bên, sát cạnh (= next to / beside)', 'The cafeteria is located adjacent to the second-floor auditoriums.'),
      w('apprise', 'v', '/əˈpraɪz/', 'báo cho biết, cung cấp thông tin (= inform / notify)', 'The plant manager apprised the board of directors of recent productivity gains.'),
      w('mandate', 'v', '/ˈmændeɪt/', 'ra lệnh bắt buộc thi hành (= require / stipulate)', 'New city building codes mandate solar panel installation on all new commercial structures.'),
      w('procure', 'v', '/prəˈkjʊə(r)/', 'mua sắm vật tư, trang thiết bị (= obtain / acquire)', 'The purchasing department worked overtime to procure emergency medical face masks.'),
      w('subsequent', 'adj', '/ˈsʌbsɪkwənt/', 'tiếp sau đó, xảy ra sau (= following / later)', 'Initial trials were inconclusive, but subsequent tests proved remarkably effective.'),
      w('unprecedented', 'adj', '/ʌnˈpresɪdentɪd/', 'chưa từng có tiền lệ trong lịch sử (= novel)', 'Soaring online holiday retail orders surged to an unprecedented all-time record.'),
      w('shortfall', 'n', '/ˈʃɔːtfɔːl/', 'sự thiếu hụt số tiền/sản lượng (= deficit)', 'A three-million-dollar tax shortfall forced the municipality to pause road repaving.'),
      w('versatile', 'adj', '/ˈvɜːsətaɪl/', 'đa năng, thích ứng linh hoạt (= adaptable / flexible)', 'The new laser-cutting apparatus is versatile enough to slice metals, ceramics, and wood.'),
      w('lucrative', 'adj', '/ˈluːkrətɪv/', 'siêu lợi nhuận, kiếm nhiều tiền (= profitable)', 'The telecommunications conglomerate landed a lucrative five-year government satellite deal.'),
      w('defect', 'n', '/ˈdiːfekt/', 'khuyết tật lỗi sản phẩm (= imperfection / flaw)', 'Engineers detected a minor metallurgical defect in the front axle casing.'),
      w('prerequisite', 'n, adj', '/ˌpriːˈrekwəzɪt/', 'điều kiện tiên quyết bắt buộc (= requirement)', 'Fluent spoken Spanish is a prerequisite qualification for the South American sales post.'),
      w('rescind', 'v', '/rɪˈsɪnd/', 'hủy bỏ bãi bỏ hiệu lực hợp đồng (= cancel / revoke)', 'The buyer reserved the legal right to rescind the purchase pact if title deed issues arose.'),
      w('inconsequential', 'adj', '/ɪnˌkɒnsɪˈkwenʃl/', 'không đáng kể, không quan trọng (= trivial / minor)', 'The slight difference in cabin noise was deemed inconsequential by test drivers.')
    ]
  }
];
