import { w } from './helper.js';

export const unitsPart2 = [
  {
    id: 12,
    title: 'Chuyến công tác, Đặt vé & Lưu trú (Business Travel, Booking & Accommodation)',
    words: [
      w('itinerary', 'n', '/aɪˈtɪnərəri/', 'lịch trình chi tiết chuyến đi/công tác', 'The executive assistant prepared a detailed travel itinerary for the European tour.'),
      w('accommodation', 'n', '/əˌkɒməˈdeɪʃn/', 'chỗ ăn ở, phòng nghỉ lưu trú', 'Hotel accommodations near the convention center have been fully booked.'),
      w('boarding pass', 'n phr', '/ˈbɔːdɪŋ pɑːs/', 'thẻ lên máy bay', 'Passengers must show their boarding pass and valid passport at the gate.'),
      w('layover', 'n', '/ˈleɪəʊvə(r)/', 'thời gian quá cảnh, dừng nghỉ giữa chuyến bay', 'We have a three-hour layover in Tokyo before our connecting flight to Sydney.'),
      w('concierge', 'n', '/kɔːnˈsiːeəʒ/', 'nhân viên hỗ trợ tiền sảnh khách sạn', 'The hotel concierge arranged chauffeured airport transfers and dinner reservations.'),
      w('carry-on', 'n, adj', '/ˈkæri ɒn/', 'hành lý xách tay đem lên khoang', 'Airlines strictly enforce weight limits for carry-on luggage.'),
      w('checked luggage', 'n phr', '/tʃekt ˈlʌɡɪdʒ/', 'hành lý ký gửi dưới khoang hàng', 'Passengers are allowed two pieces of checked luggage free of charge.'),
      w('delayed', 'adj', '/dɪˈleɪd/', 'bị hoãn lại, chậm trễ lịch trình', 'The evening flight to Chicago was delayed due to severe thunderstorms.'),
      w('rebooking fee', 'n phr', '/riːˈbʊkɪŋ fiː/', 'phí đổi lịch trình chuyến bay', 'Passengers were exempt from rebooking fees after the blizzard canceled departures.'),
      w('commute', 'v, n', '/kəˈmjuːt/', 'đi lại hằng ngày từ nhà đến nơi làm việc', 'Many suburban professionals commute forty minutes by commuter rail each morning.'),
      w('fare', 'n', '/feə(r)/', 'tiền vé tàu/xe/máy bay', 'The airline offers discounted round-trip airfare during off-peak seasons.'),
      w('hospitality', 'n', '/ˌhɒspɪˈtæləti/', 'ngành dịch vụ hiếu khách (khách sạn, du lịch)', 'The city’s hospitality industry welcomed hundreds of international delegates.'),
      w('amenity', 'n', '/əˈmiːnəti/', 'tiện nghi dịch vụ (hồ bơi, wifi, phòng gym)', 'Complimentary high-speed Wi-Fi is among the hotel’s most popular amenities.'),
      w('shuttle', 'n, v', '/ˈʃʌtl/', 'xe đưa đón tuyến cố định; đưa đón qua lại', 'A complimentary airport shuttle runs between the terminal and hotel every 20 minutes.'),
      w('reservation', 'n', '/ˌrezəˈveɪʃn/', 'sự đặt chỗ trước (phòng, vé, bàn)', 'Please confirm your flight reservation at least 48 hours prior to departure.'),
      w('no-show', 'n', '/ˈnəʊ ʃəʊ/', 'khách đã đặt phòng nhưng không đến nhận', 'A penalty fee is charged for each hotel no-show during peak tourist season.'),
      w('customs declaration', 'n phr', '/ˈkʌstəmz ˌdekləˈreɪʃn/', 'tờ khai hải quan nhập cảnh', 'Travelers must complete a customs declaration form before arriving at immigration.'),
      w('jet lag', 'n', '/ˈdʒet læɡ/', 'sự mệt mỏi do chênh lệch múi giờ', 'Drinking plenty of water helps travelers alleviate the symptoms of jet lag.'),
      w('per diem', 'n phr, adv', '/pɜː ˈdaɪem/', 'tiền công tác phí khoán theo ngày', 'Employees traveling abroad receive a daily per diem for meals and incidental expenses.'),
      w('incidental', 'n, adj', '/ˌɪnsɪˈdentl/', 'chi phí phụ phát sinh trong chuyến đi', 'The company credit card covers hotel rooms, but guests pay for personal incidentals.'),
      w('excursion', 'n', '/ɪkˈskɜːʃn/', 'chuyến tham quan ngắn ngày', 'The conference organizers scheduled a cultural excursion to historical landmarks.'),
      w('charter', 'v, n', '/ˈtʃɑːtə(r)/', 'thuê riêng trọn gói (máy bay, xe buýt)', 'The corporation chartered a private jet to transport executive board members.'),
      w('standby', 'n, adj', '/ˈstændbaɪ/', 'vé chờ máy bay giờ chót', 'Travelers holding standby tickets were boarded on the later evening flight.'),
      w('terminal', 'n', '/ˈtɜːmɪnl/', 'nhà ga sân bay, bến đón trả khách', 'International departures take place exclusively from Terminal 2.'),
      w('excess baggage', 'n phr', '/ɪkˈses ˈbæɡɪdʒ/', 'hành lý vượt quá trọng lượng cho phép', 'Travelers must pay hefty fees for any excess baggage exceeding 23 kilograms.'),
      w('suite', 'n', '/swiːt/', 'dãy phòng khách sạn cao cấp liên thông', 'The keynote speaker was accommodated in the hotel’s executive presidential suite.'),
      w('check-in', 'n, v', '/ˈtʃek ɪn/', 'thủ tục nhận phòng / làm thủ tục bay', 'Online check-in opens 24 hours prior to scheduled departure times.'),
      w('check-out', 'n, v', '/ˈtʃek aʊt/', 'thủ tục trả phòng khách sạn', 'Late check-out may be requested at the reception desk subject to availability.'),
      w('cancellation policy', 'n phr', '/ˌkænsəˈleɪʃn ˈpɒləsi/', 'chính sách hủy phòng/vé', 'Review the hotel cancellation policy carefully before confirming non-refundable rates.'),
      w('boarding gate', 'n phr', '/ˈbɔːdɪŋ ɡeɪt/', 'cửa ra máy bay tại nhà ga', 'Passengers for flight AA204 should proceed immediately to boarding gate 12B.')
    ]
  },
  {
    id: 13,
    title: 'Hội nghị, Hội thảo & Triển lãm thương mại (Conferences, Seminars & Trade Expos)',
    words: [
      w('keynote speaker', 'n phr', '/ˈkiːnəʊt ˈspiːkə(r)/', 'diễn giả chính của hội nghị', 'Dr. Aris Thorne served as the keynote speaker at the Global AI Symposium.'),
      w('symposium', 'n', '/sɪmˈpəʊziəm/', 'hội nghị chuyên đề khoa học/kinh tế', 'The annual symposium on sustainable architecture drew architects from forty nations.'),
      w('seminar', 'n', '/ˈsemɪnɑː(r)/', 'buổi hội thảo chuyên môn, chuyên đề', 'The finance department hosted an intensive seminar on corporate tax reforms.'),
      w('panel discussion', 'n phr', '/ˈpænl dɪˈskʌʃn/', 'phiên thảo luận bàn tròn của chuyên gia', 'A panel discussion on supply chain resilience followed the opening remarks.'),
      w('attendee', 'n', '/əˌtenˈdiː/', 'người tham dự sự kiện/hội nghị', 'Over 1,200 registered attendees gathered in the main auditorium for the keynote.'),
      w('badge', 'n', '/bædʒ/', 'thẻ đại biểu tham dự hội nghị', 'Please display your conference name badge at all times to gain access to halls.'),
      w('exhibit', 'v, n', '/ɪɡˈzɪbɪt/', 'trưng bày; gian hàng triển lãm', 'Dozens of innovative tech startups will exhibit their prototypes at the expo.'),
      w('booth', 'n', '/buːð/', 'gian hàng hội chợ thương mại', 'Our marketing team designed an eye-catching booth to demonstrate the software.'),
      w('moderator', 'n', '/ˈmɒdəreɪtə(r)/', 'người điều phối phiên thảo luận', 'The panel moderator kept the debate focused and ensured equal speaking time.'),
      w('breakout session', 'n phr', '/ˈbreɪkaʊt ˈseʃn/', 'phiên thảo luận nhóm nhỏ chuyên sâu', 'Attendees divided into breakout sessions to brainstorm practical marketing strategies.'),
      w('convention', 'n', '/kənˈvenʃn/', 'đại hội, hội nghị thường niên quy mô lớn', 'The national medical convention takes place at the convention center in Dallas.'),
      w('handout', 'n', '/ˈhændaʊt/', 'tài liệu phát tay cho người dự', 'Organizers distributed informative handouts summarizing the presenter’s findings.'),
      w('podium', 'n', '/ˈpəʊdiəm/', 'bục phát biểu của diễn giả', 'The CEO stepped up to the podium to announce the revolutionary new product line.'),
      w('registration fee', 'n phr', '/ˌredʒɪˈstreɪʃn fiː/', 'phí đăng ký tham dự hội thảo', 'Early-bird registration fees offer a 25% discount through the end of the month.'),
      w('networking', 'n', '/ˈnetwɜːkɪŋ/', 'giao lưu kết nối quan hệ kinh doanh', 'The evening cocktail reception provided valuable networking opportunities for executives.'),
      w('venue', 'n', '/ˈvenjuː/', 'địa điểm tổ chức sự kiện', 'The historic downtown opera house proved to be a magnificent venue for the gala.'),
      w('program', 'n', '/ˈprəʊɡræm/', 'chương trình hội nghị tổng thể', 'The official convention program lists all panel speakers and workshop rooms.'),
      w('colloquium', 'n', '/kəˈləʊkwiəm/', 'buổi tọa đàm học thuật chuyên sâu', 'The economics department sponsored a colloquium on international currency flows.'),
      w('opening remarks', 'n phr', '/ˈəʊpnɪŋ rɪˈmɑːks/', 'phát biểu khai mạc sự kiện', 'The board chairman delivered the opening remarks at 9:00 sharp.'),
      w('recess', 'n, v', '/rɪˈses/', 'thời gian giải lao giữa các phiên họp', 'The committee agreed to take a thirty-minute recess before voting on amendments.'),
      w('trade show', 'n phr', '/treɪd ʃəʊ/', 'triển lãm thương mại chuyên ngành', 'Automakers unveiled experimental concept vehicles at the international trade show.'),
      w('facilitator', 'n', '/fəˈsɪlɪteɪtə(r)/', 'người hỗ trợ điều hành buổi thảo luận', 'An external facilitator helped guide the executive retreat through strategic planning.'),
      w('roundtable', 'n', '/ˈraʊndteɪbl/', 'hội nghị bàn tròn giữa các bên', 'Industry leaders held a closed-door roundtable on artificial intelligence ethics.'),
      w('keynote', 'n, adj', '/ˈkiːnəʊt/', 'bài phát biểu chủ đạo; tư tưởng cốt lõi', 'His keynote address touched upon sustainability and clean energy transition.'),
      w('showcase', 'v, n', '/ˈʃəʊkeɪs/', 'trưng bày phô diễn điểm nổi bật', 'The startup showcase highlighted the region’s ten most promising tech ventures.'),
      w('plenary session', 'n phr', '/ˈpliːnəri ˈseʃn/', 'phiên họp toàn thể hội nghị', 'All conference delegates are required to attend the morning plenary session.'),
      w('demonstration', 'n', '/ˌdemənˈstreɪʃn/', 'buổi thuyết minh thị phạm sản phẩm', 'Live demonstrations of the surgical robot drew massive crowds to booth 402.'),
      w('audio-visual', 'adj', '/ˌɔːdiəʊ ˈvɪʒuəl/', 'thuộc âm thanh và hình ảnh trình chiếu', 'The venue is outfitted with state-of-the-art audio-visual equipment.'),
      w('interpreter', 'n', '/ɪnˈtɜːprɪtə(r)/', 'thông dịch viên dịch trực tiếp tại hội nghị', 'Simultaneous interpreters translated the proceedings into six official languages.'),
      w('name tag', 'n phr', '/neɪm tæɡ/', 'thẻ đeo ghi họ tên người tham dự', 'Pick up your official badge and name tag at the registration desk upon arrival.')
    ]
  },
  {
    id: 14,
    title: 'Bất động sản thương mại & Thuê mặt bằng (Commercial Real Estate & Leasing)',
    words: [
      w('lease', 'n, v', '/liːs/', 'hợp đồng thuê dài hạn; cho thuê dài hạn', 'The tech startup signed a five-year lease for three floors in the downtown tower.'),
      w('tenant', 'n', '/ˈtenənt/', 'người thuê nhà/văn phòng', 'Commercial tenants are responsible for their internal utility and internet expenses.'),
      w('landlord', 'n', '/ˈlændlɔːd/', 'chủ nhà, chủ tòa nhà cho thuê', 'The landlord agreed to replace the central heating unit before winter begins.'),
      w('premises', 'n (pl)', '/ˈpremɪsɪz/', 'khuôn viên, cơ sở mặt bằng', 'Smoking and unauthorized photography are strictly prohibited on company premises.'),
      w('property', 'n', '/ˈprɒpəti/', 'bất động sản, tài sản địa ốc', 'Commercial property values along the riverfront corridor surged over the past year.'),
      w('occupancy', 'n', '/ˈɒkjəpənsi/', 'tỷ lệ lấp đầy mặt bằng văn phòng', 'The office building boasts an impressive 98% average occupancy rate.'),
      w('eviction', 'n', '/ɪˈvɪkʃn/', 'sự cưỡng chế trục xuất người thuê', 'The landlord issued an eviction notice after four consecutive months of unpaid rent.'),
      w('sublet', 'v', '/ˌsʌbˈlet/', 'cho thuê lại mặt bằng (thuê thứ cấp)', 'Tenants must obtain written consent from the landlord before subletting any space.'),
      w('renovate', 'v', '/ˈrenəveɪt/', 'cải tạo, tân trang lại mặt bằng', 'Management plans to renovate the cafeteria and lobby during the holiday break.'),
      w('security deposit', 'n phr', '/sɪˈkjʊərəti dɪˈpɒzɪt/', 'tiền đặt cọc bảo đảm hợp đồng thuê', 'A security deposit equivalent to two months’ rent is payable upon signing.'),
      w('real estate', 'n phr', '/ˈriːəl ɪsteɪt/', 'ngành bất động sản, địa ốc', 'A prominent real estate agency handled negotiations for the corporate headquarters.'),
      w('zoning', 'n', '/ˈzəʊnɪŋ/', 'quy hoạch phân vùng sử dụng đất', 'City zoning regulations forbid manufacturing facilities in residential neighborhoods.'),
      w('valuation', 'n', '/ˌvæljuˈeɪʃn/', 'sự định giá giá trị bất động sản', 'A formal market valuation was conducted prior to putting the property up for sale.'),
      w('mortgage', 'n, v', '/ˈmɔːɡɪdʒ/', 'khoản vay thế chấp mua nhà đất', 'The developer secured a 20-year commercial mortgage at a competitive fixed rate.'),
      w('title deed', 'n phr', '/ˈtaɪtl diːd/', 'giấy chứng nhận quyền sở hữu nhà đất (sổ đỏ)', 'The buyer must inspect the title deed to verify ownership boundaries.'),
      w('square footage', 'n phr', '/skweə ˈfʊtɪdʒ/', 'diện tích mặt bằng tính theo foot vuông', 'The new distribution center provides over 200,000 square feet of storage space.'),
      w('refurbish', 'v', '/ˌriːˈfɜːbɪʃ/', 'tân trang làm mới nội thất cơ sở', 'Architects completely refurbished the historic brick warehouse into modern lofts.'),
      w('commercial lease', 'n phr', '/kəˈmɜːʃl liːs/', 'hợp đồng thuê mặt bằng kinh doanh', 'Review the escalation clause in your commercial lease before signing the agreement.'),
      w('utilities', 'n (pl)', '/juːˈtɪlətiz/', 'dịch vụ điện, nước, khí đốt công cộng', 'Monthly utility bills are split evenly among all tenants on the second floor.'),
      w('relocate', 'v', '/ˌriːləʊˈkeɪt/', 'chuyển trụ sở/địa điểm hoạt động', 'The software firm will relocate its headquarters to Austin by the end of Q3.'),
      w('prime location', 'n phr', '/praɪm ləʊˈkeɪʃn/', 'vị trí đắc địa, khu đất vàng', 'The department store occupies a prime location right opposite the central station.'),
      w('vacate', 'v', '/vəˈkeɪt/', 'dọn đi, trả lại mặt bằng trống', 'Tenants are required to vacate the premises by midnight on the final day of lease.'),
      w('landowner', 'n', '/ˈlændəʊnə(r)/', 'chủ sở hữu đất đai', 'The local landowner leased sixty acres of farmland for a new solar array.'),
      w('spatial', 'adj', '/ˈspeɪʃl/', 'thuộc về không gian kiến trúc', 'The interior designer optimized the spatial layout to encourage team collaboration.'),
      w('property tax', 'n phr', '/ˈprɒpəti tæks/', 'thuế bất động sản địa ốc', 'Commercial property taxes are reassessed annually by municipal authorities.'),
      w('fixture', 'n', '/ˈfɪkstʃə(r)/', 'vật cố định gắn liền với nhà (đèn, bồn rửa)', 'Lighting fixtures and built-in shelving remain property of the landlord upon departure.'),
      w('dilapidated', 'adj', '/dɪˈlæpɪdeɪtɪd/', 'xuống cấp, xập xệ do không bảo dưỡng', 'The dilapidated warehouse was condemned and scheduled for complete demolition.'),
      w('occupant', 'n', '/ˈɒkjəpənt/', 'người đang cư ngụ/sử dụng mặt bằng', 'Previous occupants left the executive offices in clean and orderly condition.'),
      w('escrow', 'n', '/ˈeskrəʊ/', 'tài khoản ký quỹ trung gian đảm bảo', 'Earnest money was deposited into an escrow account pending title verification.'),
      w('demolition', 'n', '/ˌdeməˈlɪʃn/', 'sự phá dỡ công trình cũ để xây mới', 'Demolition crews tore down the condemned factory to make way for high-rise condos.')
    ]
  },
  {
    id: 15,
    title: 'Quản lý cơ sở vật chất, Bảo trì & Sửa chữa (Facilities Management & Maintenance)',
    words: [
      w('facility', 'n', '/fəˈsɪləti/', 'cơ sở hạ tầng, cơ sở vật chất', 'Our manufacturing facility in Detroit operates on a three-shift schedule.'),
      w('maintenance', 'n', '/ˈmeɪntənəns/', 'công tác bảo trì, bảo dưỡng kỹ thuật', 'Routine maintenance of elevators is scheduled every second Saturday morning.'),
      w('inspection', 'n', '/ɪnˈspekʃn/', 'sự thanh tra, kiểm tra kỹ thuật định kỳ', 'City fire inspectors carried out an annual inspection of the sprinkler system.'),
      w('plumbing', 'n', '/ˈplʌmɪŋ/', 'hệ thống đường ống dẫn nước', 'A plumbing leak on the third floor caused minor ceiling damage in the conference room.'),
      w('ventilation', 'n', '/ˌventɪˈleɪʃn/', 'hệ thống thông gió làm thoáng khí', 'Modern office towers feature advanced ventilation filters to ensure clean indoor air.'),
      w('air conditioning', 'n phr', '/ˈeə kəndɪʃənɪŋ/', 'hệ thống điều hòa nhiệt độ (HVAC)', 'The air conditioning was shut off over the weekend for filter replacement.'),
      w('janitor', 'n', '/ˈdʒænɪtə(r)/', 'nhân viên lao công tạp vụ tòa nhà', 'The night janitor vacuums carpets and empties wastebaskets across all floors.'),
      w('custodian', 'n', '/kʌˈstəʊdiən/', 'người quản lý trông nom cơ sở vật chất', 'Building custodians ensure security gates are locked following evening seminars.'),
      w('sanitation', 'n', '/ˌsænɪˈteɪʃn/', 'vệ sinh môi trường công cộng', 'Strict sanitation guidelines are enforced throughout the commercial kitchen.'),
      w('renovation', 'n', '/ˌrenəˈveɪʃn/', 'công cuộc cải tạo nâng cấp cơ sở', 'The corporate library is closed temporarily for extensive acoustic renovations.'),
      w('deterioration', 'n', '/dɪˌtɪəriəˈreɪʃn/', 'sự xuống cấp, mục nát theo thời gian', 'Moisture buildup caused rapid structural deterioration of the basement timbers.'),
      w('circuit breaker', 'n phr', '/ˈsɜːkɪt ˈbreɪkə(r)/', 'cầu dao ngắt điện tự động', 'Overloading electrical outlets will trip the circuit breaker in the utility closet.'),
      w('power surge', 'n phr', '/ˈpaʊə sɜːdʒ/', 'sự xung áp điện đột ngột', 'Surge protectors safeguard valuable office computers against sudden power surges.'),
      w('generator', 'n', '/ˈdʒenəreɪtə(r)/', 'máy phát điện dự phòng', 'An emergency backup generator kicked in within seconds of the regional blackout.'),
      w('thermostat', 'n', '/ˈθɜːməstæt/', 'bộ điều nhiệt tự động', 'Please adjust the digital thermostat to 22 degrees Celsius during business hours.'),
      w('overhaul', 'v, n', '/ˌəʊvəˈhɔːl/', 'đại tu, kiểm tra sửa chữa toàn diện', 'Technicians will overhaul the central boiler before freezing weather arrives.'),
      w('preventive', 'adj', '/prɪˈventɪv/', 'mang tính phòng ngừa sự cố', 'Regular oil changes and filter swaps are essential parts of preventive maintenance.'),
      w('breakdown', 'n', '/ˈbreɪkdaʊn/', 'sự hỏng hóc, chết máy đột ngột', 'A sudden mechanical breakdown halted elevator operations for three hours.'),
      w('technician', 'n', '/tekˈnɪʃn/', 'chuyên viên kỹ thuật, thợ máy', 'A certified HVAC technician was summoned to inspect the malfunctioning chiller.'),
      w('disinfect', 'v', '/ˌdɪsɪnˈfekt/', 'khử trùng, sát khuẩn bề mặt', 'Cleaning crews disinfect shared meeting room tables between consecutive presentations.'),
      w('exterminator', 'n', '/ɪkˈstɜːmɪneɪtə(r)/', 'thợ diệt côn trùng dịch hại', 'An exterminator treats the basement perimeter twice a year to deter pests.'),
      w('sewage', 'n', '/ˈsuːɪdʒ/', 'hệ thống nước thải sinh hoạt', 'Municipal workers repaired a damaged sewer main outside the office complex.'),
      w('infrastructure', 'n', '/ˈɪnfrəstrʌktʃə(r)/', 'cơ sở hạ tầng cơ bản (điện đường nước)', 'Investing in telecommunication infrastructure helped expand high-speed fiber access.'),
      w('retrofit', 'v', '/ˈretrəʊfɪt/', 'lắp thêm trang thiết bị mới vào cơ sở cũ', 'Engineers retrofitted the 1970s office block with energy-efficient double glazing.'),
      w('upkeep', 'n', '/ˈʌpkiːp/', 'chi phí duy tu, bảo dưỡng định kỳ', 'The university spends substantial funds each semester on the upkeep of grounds.'),
      w('repairs', 'n (pl)', '/rɪˈpeəz/', 'công việc sửa chữa bảo trì', 'The parking garage is closed for structural concrete repairs until Friday.'),
      w('deteriorate', 'v', '/dɪˈtɪəriəreɪt/', 'xuống cấp, suy thoái chất lượng', 'Without regular weather sealing, wooden window frames rapidly deteriorate.'),
      w('cleanroom', 'n', '/ˈkliːnruːm/', 'phòng sạch tiệt trùng chế tạo vi mạch', 'Specialist cleanroom facilities prevent microscopic dust from ruining microchips.'),
      w('fire extinguisher', 'n phr', '/ˈfaɪər ɪkˈstɪŋɡwɪʃə(r)/', 'bình chữa cháy cầm tay', 'Fire extinguishers are stationed next to every emergency exit stairway.'),
      w('evacuation', 'n', '/ɪˌvækjuˈeɪʃn/', 'sự sơ tán khẩn cấp khỏi tòa nhà', 'Employees assembled in the north parking lot during the unannounced evacuation drill.')
    ]
  },
  {
    id: 16,
    title: 'Sản xuất, Dây chuyền & Gia công (Manufacturing & Assembly Line)',
    words: [
      w('assembly line', 'n phr', '/əˈsembli laɪn/', 'dây chuyền lắp ráp tự động', 'Robotic arms on the assembly line can mount automotive doors in forty seconds.'),
      w('manufacture', 'v, n', '/ˌmænjuˈfæktʃə(r)/', 'sản xuất công nghiệp; ngành sản xuất', 'The factory manufactures medical diagnostic equipment for global export.'),
      w('component', 'n', '/kəmˈpəʊnənt/', 'linh kiện, bộ phận cấu thành', 'Each electronic component is rigorously inspected prior to final chassis assembly.'),
      w('raw material', 'n phr', '/rɔː məˈtɪəriəl/', 'nguyên liệu thô ban đầu', 'Rising international costs for raw materials forced prices up by twelve percent.'),
      w('output', 'n', '/ˈaʊtpʊt/', 'sản lượng đầu ra sản xuất', 'Factory output reached a record high of 50,000 units this past quarter.'),
      w('capacity', 'n', '/kəˈpæsəti/', 'công suất sản xuất tối đa', 'The steel mill is operating at 95% capacity to satisfy soaring infrastructure demand.'),
      w('bottleneck', 'n', '/ˈbɒtlnek/', 'điểm nghẽn gây chậm cả dây chuyền', 'The packaging station turned out to be the primary bottleneck in manufacturing.'),
      w('robotics', 'n', '/rəʊˈbɒtɪks/', 'công nghệ robot chế tạo tự động', 'Investing in factory robotics streamlined the automobile door assembly line.'),
      w('machinery', 'n', '/məˈʃiːnəri/', 'máy móc thiết bị sản xuất nặng', 'Operators must don protective headgear when working near heavy stamping machinery.'),
      w('fabricate', 'v', '/ˈfæbrɪkeɪt/', 'chế tạo, gia công cơ khí chính xác', 'Specialized CNC lasers fabricate titanium aircraft brackets within tiny tolerances.'),
      w('subcontractor', 'n', '/ˌsʌbkənˈtræktə(r)/', 'nhà thầu phụ gia công linh kiện', 'The primary contractor hired subcontractors to handle precision electronic soldering.'),
      w('prototype', 'n', '/ˈprəʊtətaɪp/', 'mẫu thử nghiệm đầu tiên (nguyên mẫu)', 'Engineers put the battery prototype through extreme temperature durability tests.'),
      w('production quota', 'n phr', '/prəˈdʌkʃn ˈkwəʊtə/', 'chỉ tiêu sản lượng sản xuất', 'The night shift easily exceeded its daily production quota by 150 units.'),
      w('idle time', 'n phr', '/ˈaɪdl taɪm/', 'thời gian máy móc ngừng nghỉ chờ hàng', 'Optimizing tool changeovers minimized costly machine idle time.'),
      w('throughput', 'n', '/ˈθruːpʊt/', 'lượng sản phẩm xử lý qua hệ thống', 'Upgraded hydraulic pumps doubled the chemical plant’s processing throughput.'),
      w('foundry', 'n', '/ˈfaʊndri/', 'xưởng đúc kim loại/chế tạo bán dẫn', 'The semiconductor foundry produces millions of microprocessors every week.'),
      w('standardize', 'v', '/ˈstændədaɪz/', 'tiêu chuẩn hóa quy trình kỹ thuật', 'We standardized screw sizes across all product lines to simplify manufacturing.'),
      w('conveyor belt', 'n phr', '/kənˈveɪə belt/', 'băng chuyền tải hàng sản xuất', 'Cartons glide down the conveyor belt directly into the automated palletizer.'),
      w('wear', 'n', '/weə(r)/', 'sự hao mòn của lưỡi cắt/linh kiện máy', 'Tool wear was monitored continuously by vibration and acoustic sensors.'),
      w('mass production', 'n phr', '/mæs prəˈdʌkʃn/', 'sản xuất hàng loạt quy mô công nghiệp', 'Mass production of the new electric crossover will commence early next spring.'),
      w('plant', 'n', '/plɑːnt/', 'nhà máy công nghiệp quy mô lớn', 'The chemical processing plant underwent a comprehensive environmental audit.'),
      w('retooling', 'n', '/ˌriːˈtuːlɪŋ/', 'thay đổi dây chuyền công cụ chế tạo mới', 'The assembly plant underwent a three-week retooling to manufacture electric vehicles.'),
      w('defect rate', 'n phr', '/ˈdiːfekt reɪt/', 'tỷ lệ sản phẩm lỗi hỏng', 'Precision calibration helped reduce the factory’s defect rate to under 0.02%.'),
      w('machinist', 'n', '/məˈʃiːnɪst/', 'thợ cơ khí vận hành máy tiện/phay', 'A skilled machinist programmed the multi-axis lathe to sculpt turbine blades.'),
      w('lot number', 'n phr', '/lɒt ˈnʌmbə(r)/', 'số lô sản phẩm sản xuất để truy xuất', 'Inspect the printed lot number on the packaging if reporting a defective batch.'),
      w('workforce', 'n', '/ˈwɜːkfɔːs/', 'lực lượng lao động nhà máy', 'The manufacturing plant employs a skilled workforce of over eight hundred technicians.'),
      w('custom-made', 'adj', '/ˌkʌstəm ˈmeɪd/', 'sản xuất đặt riêng theo yêu cầu', 'The client ordered custom-made stainless-steel fittings for their brewery.'),
      w('shift', 'n', '/ʃɪft/', 'ca làm việc tại nhà máy', 'Factory operators work rotating eight-hour shifts to keep production humming.'),
      w('supply chain', 'n phr', '/səˈplaɪ tʃeɪn/', 'chuỗi cung ứng sản xuất', 'Disruptions in the overseas supply chain delayed automobile delivery dates.'),
      w('silo', 'n', '/ˈsaɪləʊ/', 'tháp/kho silo chứa vật liệu rời', 'Grain and industrial plastics are stored in high-capacity vertical silos.')
    ]
  },
  {
    id: 17,
    title: 'Kiểm soát chất lượng & Tiêu chuẩn ISO (Quality Control & Compliance)',
    words: [
      w('quality control', 'n phr', '/ˈkwɒləti kənˈtrəʊl/', 'kiểm soát chất lượng sản phẩm (QC)', 'The quality control team conducts random sample testing on every finished batch.'),
      w('compliance', 'n', '/kəmˈplaɪəns/', 'sự tuân thủ tiêu chuẩn, quy chuẩn luật', 'Our factories operate in strict compliance with federal environmental laws.'),
      w('surveillance', 'n', '/sɜːˈveɪləns/', 'sự giám sát theo dõi quy trình kỹ thuật', 'Continuous video surveillance ensures that cleanroom clean standards are maintained.'),
      w('standard', 'n', '/ˈstændəd/', 'tiêu chuẩn chất lượng/kỹ thuật', 'Products must meet international ISO 9001 standards to earn certification.'),
      w('calibration', 'n', '/ˌkælɪˈbreɪʃn/', 'sự hiệu chuẩn đo lường chính xác', 'Laser measurement tools require bi-monthly calibration by certified technicians.'),
      w('flaw', 'n', '/flɔː/', 'tì vết, khuyết tật nhỏ của sản phẩm', 'Microscopic camera sensors detect the slightest optical flaws on glass lenses.'),
      w('tolerance', 'n', '/ˈtɒlərəns/', 'dung sai kỹ thuật cho phép', 'Aerospace parts must be machined within a microscopic tolerance of 0.005 mm.'),
      w('yardstick', 'n', '/ˈjɑːdstɪk/', 'thước đo tiêu chuẩn đánh giá', 'Energy efficiency has become the primary yardstick for evaluating appliances.'),
      w('certification', 'n', '/ˌsɜːtɪfɪˈkeɪʃn/', 'chứng chỉ chứng nhận chất lượng', 'The facility attained formal certification for organic food processing.'),
      w('scrutiny', 'n', '/ˈskruːtəni/', 'sự kiểm tra xem xét kỹ lưỡng tỉ mỉ', 'The pharmaceutical company’s trial data came under intense regulatory scrutiny.'),
      w('verify', 'v', '/ˈverɪfaɪ/', 'xác minh, kiểm chứng độ chính xác', 'Auditors reviewed laboratory test logs to verify safety claims.'),
      w('adhere to', 'phr v', '/ədˈhɪə tuː/', 'tuân thủ nghiêm ngặt tiêu chuẩn', 'All contract assemblers must strictly adhere to statutory hygiene protocols.'),
      w('discard', 'v', '/dɪˈskɑːd/', 'loại bỏ, vứt bỏ hàng không đạt chuẩn', 'Any canned goods showing signs of denting or seal damage must be discarded.'),
      w('rigorous', 'adj', '/ˈrɪɡərəs/', 'khắt khe, nghiêm ngặt, chuẩn xác', 'The vaccine underwent months of rigorous clinical testing before market approval.'),
      w('peer review', 'n phr', '/pɪə rɪˈvjuː/', 'đánh giá chéo ngang hàng giữa các chuyên gia', 'All pharmaceutical trial protocols must pass rigorous academic peer review.'),
      w('conformity', 'n', '/kənˈfɔːməti/', 'sự phù hợp tiêu chuẩn quy định', 'Certificates of conformity must accompany every shipment of steel rebar.'),
      w('rectify', 'v', '/ˈrektɪfaɪ/', 'chỉnh sửa, khắc phục sai sót kỹ thuật', 'The engineering team acted immediately to rectify the firmware vulnerability.'),
      w('paramount', 'adj', '/ˈpærəmaʊnt/', 'tối quan trọng, có ý nghĩa hàng đầu', 'Worker safety and product integrity are of paramount importance to our executive board.'),
      w('substandard', 'adj', '/ˌsʌbˈstændəd/', 'dưới chuẩn, kém chất lượng không đạt yêu cầu', 'Substandard building materials were rejected by the head structural engineer.'),
      w('sampling', 'n', '/ˈsɑːmplɪŋ/', 'hoạt động lấy mẫu kiểm tra ngẫu nhiên', 'Statistical sampling allows quality managers to evaluate millions of pills swiftly.'),
      w('deviation', 'n', '/ˌdiːviˈeɪʃn/', 'độ lệch chuẩn so với thông số thiết kế', 'Any deviation greater than two millimeters results in immediate part rejection.'),
      w('integrity', 'n', '/ɪnˈteɡrəti/', 'sự vẹn toàn, tính toàn vẹn kết cấu', 'Ultrasonic sensors test the structural integrity of welded airplane wings.'),
      w('procedural guideline', 'n phr', '/prəˈsiːdʒərəl ˈɡaɪdlaɪn/', 'hướng dẫn quy trình thao tác chuẩn', 'Lab technicians must follow procedural guidelines for hazardous waste disposal.'),
      w('accreditation', 'n', '/əˌkredɪˈteɪʃn/', 'sự kiểm định công nhận chất lượng', 'The testing laboratory achieved ISO/IEC 17025 accreditation for forensic analysis.'),
      w('rejection rate', 'n phr', '/rɪˈdʒekʃn reɪt/', 'tỷ lệ từ chối loại bỏ hàng lỗi', 'Automating the solder line reduced the component rejection rate to near zero.'),
      w('tolerance limit', 'n phr', '/ˈtɒlərəns ˈlɪmɪt/', 'giới hạn dung sai kích thước cho phép', 'Components that exceed strict tolerance limits are immediately melted down.'),
      w('traceability', 'n', '/ˌtreɪsəˈbɪləti/', 'khả năng truy xuất nguồn gốc sản phẩm', 'Barcoding every crate guarantees end-to-end traceability across the supply chain.'),
      w('recall', 'v, n', '/rɪˈkɔːl/', 'thu hồi sản phẩm lỗi khỏi thị trường', 'The automaker issued a voluntary recall of 40,000 SUVs to fix brake software.'),
      w('negligible', 'adj', '/ˈneɡlɪdʒəbl/', 'không đáng kể, nằm trong sai số cho phép', 'The deviation in chemical density was considered negligible by senior chemists.'),
      w('seal of approval', 'n phr', '/siːl əv əˈpruːvl/', 'dấu chứng nhận đạt chuẩn chất lượng', 'The organic skincare brand proudly bears the national dermatology seal of approval.')
    ]
  },
  {
    id: 18,
    title: 'An toàn lao động, Y tế & Môi trường (Workplace Safety, Health & Ergonomics)',
    words: [
      w('hazard', 'n', '/ˈhæzəd/', 'mối nguy hiểm, rủi ro an toàn', 'Exposed electrical cabling on the construction site poses a severe tripping hazard.'),
      w('protective gear', 'n phr', '/prəˈtektɪv ɡɪə(r)/', 'đồ bảo hộ lao động cá nhân (PPE)', 'Visitors must wear protective gear including hard hats, earplugs, and steel-toe boots.'),
      w('precaution', 'n', '/prɪˈkɔːʃn/', 'biện pháp phòng ngừa tai nạn', 'Take necessary fire precautions when welding near combustible storage tanks.'),
      w('lumbar support', 'n phr', '/ˈlʌmbə səˈpɔːt/', 'đệm đỡ thắt lưng chống đau mỏi cột sống', 'Office chairs with adjustable lumbar support reduce lower back strain significantly.'),
      w('muster point', 'n phr', '/ˈmʌstə pɔɪnt/', 'điểm tập kết an toàn khi xảy ra hỏa hoạn', 'During the alarm, all refinery staff must report to designated muster point C.'),
      w('first aid', 'n phr', '/ˌfɜːst ˈeɪd/', 'sơ cấp cứu tại chỗ', 'Fully stocked first aid kits are installed in every departmental breakroom.'),
      w('fatigue', 'n', '/fəˈtiːɡ/', 'sự mệt mỏi, kiệt sức do làm việc', 'Truck drivers must log mandatory rest breaks to combat driver fatigue and accidents.'),
      w('drill', 'n', '/drɪl/', 'buổi diễn tập phòng cháy chữa cháy', 'The skyscraper hosts an unannounced annual fire drill each September.'),
      w('exhaust hood', 'n phr', '/ɪɡˈzɔːst hʊd/', 'chụp hút mùi, hút khí độc công nghiệp', 'Welders must switch on the exhaust hood before cutting galvanized metal.'),
      w('contamination', 'n', '/kənˌtæmɪˈneɪʃn/', 'sự lây nhiễm, nhiễm độc môi trường', 'Protective full-body suits prevent microbiological contamination in cleanrooms.'),
      w('injury', 'n', '/ˈɪndʒəri/', 'chấn thương lao động', 'Workplace injury rates plummeted after management mandated hardhat usage.'),
      w('disability benefits', 'n phr', '/ˌdɪsəˈbɪləti ˈbenɪfɪts/', 'trợ cấp thương tật mất sức lao động', 'Workers injured on the job are entitled to comprehensive disability benefits.'),
      w('hazardous', 'adj', '/ˈhæzədəs/', 'nguy hại, nguy hiểm độc hại', 'Special permits are required to haul hazardous industrial chemical solvents.'),
      w('eyewash station', 'n phr', '/ˈaɪwɒʃ ˈsteɪʃn/', 'trạm rửa mắt khẩn cấp trong xưởng', 'Workers splashed by battery acid must flush their eyes at the emergency eyewash station.'),
      w('respirator', 'n', '/ˈrespəreɪtə(r)/', 'mặt nạ phòng độc, khẩu trang thở', 'Sandblasting operators must wear full-face respirators with particulate filters.'),
      w('occupational health', 'n phr', '/ˌɒkjuˈpeɪʃənl helθ/', 'y tế và sức khỏe nghề nghiệp', 'The corporate physician conducts routine occupational health screenings for staff.'),
      w('incident report', 'n phr', '/ˈɪnsɪdənt rɪˈpɔːt/', 'biên bản ghi nhận sự cố tai nạn', 'Supervisors must file an incident report within 24 hours of any workplace collision.'),
      w('flammable', 'adj', '/ˈflæməbl/', 'dễ bốc cháy, dễ bắt lửa', 'Store flammable paint thinners in a fire-rated steel cabinet away from heat.'),
      w('spill', 'n, v', '/spɪl/', 'sự cố tràn hóa chất/dầu; làm tràn đổ', 'Deploy containment booms immediately in the event of an oil spill in the canal.'),
      w('sanitary', 'adj', '/ˈsænətri/', 'đạt điều kiện vệ sinh phòng dịch', 'Food packaging facilities are maintained in strictly sanitary conditions.'),
      w('wellness', 'n', '/ˈwelnəs/', 'chăm sóc sức khỏe thể chất & tinh thần', 'The corporate wellness program subsidizes gym passes and yoga classes for staff.'),
      w('guidelines', 'n (pl)', '/ˈɡaɪdlaɪnz/', 'hướng dẫn chỉ đạo an toàn', 'All contractors must comply with government workplace occupational guidelines.'),
      w('toxic', 'adj', '/ˈtɒksɪk/', 'có độc tố, gây nguy hại tính mạng', 'Do not enter the sealed silo without testing for toxic hydrogen sulfide buildup.'),
      w('repetitive strain', 'n phr', '/rɪˈpetətɪv streɪn/', 'chấn thương do thao tác lặp đi lặp lại', 'Proper wrist positioning on mice cushions prevents repetitive strain injuries.'),
      w('safeguard', 'n, v', '/ˈseɪfɡɑːd/', 'biện pháp bảo vệ; che chắn an toàn', 'Safety cages safeguard machine operators against flying metal shavings.'),
      w('combustible', 'adj', '/kəmˈbʌstəbl/', 'dễ cháy, bắt lửa nhanh', 'Keep combustible sawdust and wood shavings far away from welding stations.'),
      w('paramedic', 'n', '/ˌpærəˈmedɪk/', 'nhân viên cấp cứu y tế lưu động', 'Paramedics arrived within five minutes to treat the injured warehouse worker.'),
      w('defibrillator', 'n', '/diːˈfɪbrɪleɪtə(r)/', 'máy khử rung tim khẩn cấp (AED)', 'Automated external defibrillators are mounted near elevator lobbies on every floor.'),
      w('hard hat', 'n phr', '/ˈhɑːd hæt/', 'mũ bảo hộ cứng trên công trường', 'No one is admitted past the construction gate without wearing a certified hard hat.'),
      w('compliance officer', 'n phr', '/kəmˈplaɪəns ˈɒfɪsə(r)/', 'cán bộ thanh tra tuân thủ an toàn', 'The safety compliance officer inspects crane rigging gear every Monday morning.')
    ]
  },
  {
    id: 19,
    title: 'Ngân hàng, Tín dụng & Ngoại tệ (Banking, Credit & Foreign Exchange)',
    words: [
      w('collateral', 'n', '/kəˈlætərəl/', 'tài sản thế chấp để vay vốn', 'The borrower pledged commercial real estate as collateral for the business loan.'),
      w('interest rate', 'n phr', '/ˈɪntrəst reɪt/', 'lãi suất vay/tiền gửi ngân hàng', 'The central bank raised benchmark interest rates to combat rising domestic inflation.'),
      w('default', 'v, n', '/dɪˈfɔːlt/', 'vỡ nợ, không trả được nợ đúng hạn', 'If a company defaults on its commercial bonds, bondholders can seize assets.'),
      w('foreign exchange', 'n phr', '/ˈfɒrən ɪksˈtʃeɪndʒ/', 'ngoại hối, giao dịch đổi ngoại tệ (Forex)', 'Multi-national exporters use foreign exchange hedges to protect against currency swings.'),
      w('line of credit', 'n phr', '/laɪn əv ˈkredɪt/', 'hạn mức tín dụng ngân hàng cấp', 'The bank granted the retail chain a $5 million revolving line of credit.'),
      w('overdraft', 'n', '/ˈəʊvədrɑːft/', 'sự thấu chi tài khoản (vượt số dư)', 'Customers are charged a fee for each overdraft transaction if funds are insufficient.'),
      w('amortization', 'n', '/əˌmɔːtaɪˈzeɪʃn/', 'sự khấu hao trả góp dần nợ gốc', 'The loan schedule shows amortization of the debt over a 25-year period.'),
      w('remittance', 'n', '/rɪˈmɪtns/', 'khoản tiền chuyển khoản/chuyển ra nước ngoài', 'Overseas workers send billions in remittances back to their families annually.'),
      w('maturity date', 'n phr', '/məˈtʃʊərəti deɪt/', 'ngày đáo hạn hợp đồng tiền gửi/trái phiếu', 'The 5-year certificate of deposit will reach its maturity date next month.'),
      w('teller', 'n', '/ˈtelə(r)/', 'giao dịch viên tại quầy ngân hàng', 'The bank teller verified the customer’s identity before cashing the large check.'),
      w('deposit', 'n, v', '/dɪˈpɒzɪt/', 'tiền gửi ngân hàng; gửi tiền vào', 'Customers can deposit checks directly using our secure mobile banking app.'),
      w('withdraw', 'v', '/wɪðˈdrɔː/', 'rút tiền khỏi tài khoản ngân hàng', 'You can withdraw up to $1,000 per day from any affiliated ATM network.'),
      w('appreciation', 'n', '/əˌpriːʃiˈeɪʃn/', 'sự lên giá của đồng tiền nội tệ', 'The rapid appreciation of the yen made imported goods cheaper for domestic buyers.'),
      w('devaluation', 'n', '/ˌdiːvæljuˈeɪʃn/', 'sự phá giá đồng nội tệ', 'Currency devaluation made exported domestic electronics more affordable abroad.'),
      w('creditworthiness', 'n', '/ˈkredɪtˌwɜːðinəs/', 'mức độ uy tín tín dụng của người vay', 'Lenders inspect credit scores and balance sheets to gauge a borrower’s creditworthiness.'),
      w('wire transfer', 'n phr', '/ˈwaɪə trænsfɜː(r)/', 'chuyển khoản điện tử liên ngân hàng', 'Please send payment via international wire transfer using the provided SWIFT code.'),
      w('solvency', 'n', '/ˈsɒlvənsi/', 'khả năng thanh toán nợ đến hạn', 'Regulators conduct stress tests to ensure the long-term solvency of regional banks.'),
      w('arrears', 'n (pl)', '/əˈrɪəz/', 'tiền nợ đọng quá hạn chưa trả', 'The borrower was three months in arrears on commercial mortgage repayments.'),
      w('repay', 'v', '/rɪˈpeɪ/', 'hoàn trả lại tiền vay gốc & lãi', 'The startup aims to repay its venture debt within three fiscal quarters.'),
      w('bank statement', 'n phr', '/bæŋk ˈsteɪtmənt/', 'bản sao kê tài khoản ngân hàng', 'Check your monthly bank statement regularly to detect fraudulent charges.'),
      w('underwrite', 'v', '/ˌʌndəˈraɪt/', 'bảo lãnh phát hành tín dụng/chứng khoán', 'Several major investment banks agreed to underwrite the massive initial public offering.'),
      w('principal', 'n', '/ˈprɪnsəpl/', 'tiền nợ gốc (chưa tính lãi phát sinh)', 'Early loan prepayments reduce the remaining loan principal significantly.'),
      w('cash flow', 'n phr', '/kæʃ fləʊ/', 'dòng tiền lưu chuyển của doanh nghiệp', 'Healthy operating cash flow is crucial for meeting payroll obligations.'),
      w('custody account', 'n phr', '/ˈkʌstədi əkaʊnt/', 'tài khoản lưu ký phong tỏa bảo đảm', 'Securities and gold reserves are held in a secure institutional custody account.'),
      w('debit', 'n, v', '/ˈdebɪt/', 'ghi nợ, trừ tiền vào tài khoản', 'The utility company will automatically debit your checking account on the first of every month.'),
      w('credit bureau', 'n phr', '/ˈkredɪt bjʊərəʊ/', 'cơ quan chấm điểm tín dụng', 'A late payment may be reported to national credit bureaus and lower your score.'),
      w('transaction fee', 'n phr', '/trænˈzækʃn fiː/', 'phí giao dịch chuyển khoản', 'Online bank transfers between domestic accounts incur zero transaction fees.'),
      w('savings account', 'n phr', '/ˈseɪvɪŋz əkaʊnt/', 'tài khoản tiền gửi tiết kiệm', 'High-yield savings accounts offer interest rates well above traditional checking.'),
      w('accrued interest', 'n phr', '/əˈkruːd ˈɪntrəst/', 'tiền lãi tích dồn phát sinh chưa rút', 'Bondholders receive payment for all accrued interest at the end of each semiannual cycle.'),
      w('clearinghouse', 'n', '/ˈklɪərɪŋhaʊs/', 'trung tâm thanh toán bù trừ ngân hàng', 'The automated clearinghouse processes millions of direct-deposit paychecks daily.')
    ]
  },
  {
    id: 20,
    title: 'Thị trường chứng khoán, Cổ phiếu & Đầu tư vốn (Stock Market & Investment)',
    words: [
      w('equity', 'n', '/ˈekwəti/', 'vốn chủ sở hữu, cổ phần doanh nghiệp', 'Private equity firms injected capital into the struggling European retailer.'),
      w('quarterly distribution', 'n phr', '/ˈkwɔːtəli ˌdɪstrɪˈbjuːʃn/', 'khoản chi trả chia lãi định kỳ hằng quý', 'Real estate investment trusts pay a mandatory quarterly distribution to unit holders.'),
      w('equity partner', 'n phr', '/ˈekwəti ˈpɑːtnə(r)/', 'đối tác góp vốn nắm giữ cổ phần', 'Senior equity partners share proportionally in annual firm partnership profits.'),
      w('asset allocation', 'n phr', '/ˈæset ˌæləˈkeɪʃn/', 'sự phân bổ tỷ trọng tài sản đầu tư', 'Prudent asset allocation balances high-growth stocks with conservative corporate bonds.'),
      w('volatility', 'n', '/ˌvɒləˈtɪləti/', 'độ biến động thất thường của thị trường', 'Geopolitical tensions sparked severe volatility in global crude oil and equity markets.'),
      w('initial public offering', 'n phr', '/ɪˈnɪʃl ˈpʌblɪk ˈɒfərɪŋ/', 'phát hành cổ phiếu lần đầu ra công chúng (IPO)', 'The fintech company raised $2 billion during its highly anticipated IPO on NASDAQ.'),
      w('bull market', 'n phr', '/bʊl ˈmɑːkɪt/', 'thị trường bò tót (thị trường giá lên)', 'A prolonged bull market propelled benchmark stock indexes to record all-time highs.'),
      w('bear market', 'n phr', '/beə ˈmɑːkɪt/', 'thị trường gấu (thị trường giá xuống)', 'Investors adopted defensive strategies when the tech sector entered a bear market.'),
      w('brokerage', 'n', '/ˈbrəʊkərɪdʒ/', 'công ty môi giới chứng khoán', 'Zero-commission brokerage apps made stock investing accessible to millions of retail traders.'),
      w('capital gain', 'n phr', '/ˈkæpɪtl ɡeɪn/', 'khoản thặng dư vốn khi bán cổ phiếu lãi', 'Long-term investments held over a year benefit from lower capital gains tax rates.'),
      w('blue-chip', 'adj', '/ˈbluː tʃɪp/', 'cổ phiếu hạng nhất uy tín vốn hóa lớn', 'Conservative pension funds invest heavily in blue-chip multinational enterprises.'),
      w('speculate', 'v', '/ˈspekjuleɪt/', 'đầu cơ mạo hiểm lướt sóng kiếm lời', 'Traders who speculate on currency futures face immense financial risk.'),
      w('bond', 'n', '/bɒnd/', 'trái phiếu chính phủ hoặc doanh nghiệp', 'Government bonds offer lower yields than equities but guarantee principal return.'),
      w('mutual fund', 'n phr', '/ˈmjuːtʃuəl fʌnd/', 'quỹ đầu tư tương hỗ', 'Many employees allocate a fraction of each paycheck to index mutual funds.'),
      w('venture capital', 'n phr', '/ˈventʃə ˈkæpɪtl/', 'nguồn vốn đầu tư mạo hiểm cho startup', 'Venture capital firms poured billions into generative artificial intelligence startups.'),
      w('market capitalization', 'n phr', '/ˈmɑːkɪt ˌkæpɪtəlaɪˈzeɪʃn/', 'giá trị vốn hóa thị trường', 'The tech titan became the first corporation to cross a $3 trillion market capitalization.'),
      w('rally', 'n, v', '/ˈræli/', 'sự phục hồi bật tăng mạnh của giá', 'Tech shares led an afternoon rally following better-than-expected earnings reports.'),
      w('slump', 'n, v', '/slʌmp/', 'sự sụt giá đột ngột, khủng hoảng trượt dốc', 'A sharp slump in consumer electronics demand dampened quarterly profit margins.'),
      w('insider trading', 'n phr', '/ɪnˈsaɪdə ˈtreɪdɪŋ/', 'giao dịch nội gián gian lận chứng khoán', 'Federal authorities launched a criminal investigation into alleged insider trading.'),
      w('diversification', 'n', '/daɪˌvɜːsɪfɪˈkeɪʃn/', 'đa dạng hóa danh mục đầu tư', 'Asset diversification mitigates the danger of crippling losses in any single sector.'),
      w('annualized return', 'n phr', '/ˈænjuəlaɪzd rɪˈtɜːn/', 'tỷ suất lợi nhuận quy năm', 'The technology index fund delivered a stellar 14% annualized return over five years.'),
      w('securities', 'n (pl)', '/sɪˈkjʊərətiz/', 'các loại chứng khoán (cổ phiếu, trái phiếu)', 'The Securities and Exchange Commission regulates trading to protect public investors.'),
      w('depreciate', 'v', '/dɪˈpriːʃieɪt/', 'giảm giá trị tài sản đầu tư', 'The stock depreciated by 15% after missing analyst consensus revenue estimates.'),
      w('stake', 'n', '/steɪk/', 'tỷ lệ phần trăm cổ phần nắm giữ', 'The activist investor acquired a 7% stake and demanded seats on the board.'),
      w('hedge fund', 'n phr', '/hedʒ fʌnd/', 'quỹ phòng hộ đầu tư linh hoạt', 'Hedge funds utilize complex algorithmic strategies to profit in volatile markets.'),
      w('ticker symbol', 'n phr', '/ˈtɪkə ˈsɪmbl/', 'mã niêm yết chứng khoán', 'Apple trades on the NASDAQ exchange under the ticker symbol AAPL.'),
      w('underperform', 'v', '/ˌʌndəpəˈfɔːm/', 'sinh lời kém hơn mặt bằng chung', 'The retail conglomerate has underperformed the broader S&P 500 index this year.'),
      w('outperform', 'v', '/ˌaʊtpəˈfɔːm/', 'đạt thành tích vượt trội thị trường', 'Our tech portfolio outperformed market averages by ten percentage points.'),
      w('prospectus', 'n', '/prəˈspektəs/', 'bản cáo bạch phát hành chứng khoán', 'Carefully examine the company prospectus before subscribing to the public share offer.'),
      w('fiduciary', 'adj, n', '/fɪˈdjuːʃəri/', 'thuộc trách nhiệm ủy thác tài chính', 'Investment advisors have a strict fiduciary duty to act in the best interest of clients.')
    ]
  },
  {
    id: 21,
    title: 'Thư từ thương mại, Email & Thông cáo nội bộ (Business Correspondence & Memos)',
    words: [
      w('memorandum', 'n', '/ˌmeməˈrændəm/', 'thông báo nội bộ văn phòng', 'The human resources director circulated a memorandum regarding the new dress code.'),
      w('correspondence', 'n', '/ˌkɒrəˈspɒndəns/', 'thư từ trao đổi thương mại qua lại', 'Please archive all client correspondence relating to the trademark lawsuit.'),
      w('query', 'n', '/ˈkwɪəri/', 'thắc mắc cần tra cứu giải đáp', 'Our customer support helpdesk handles hundreds of billing queries every morning.'),
      w('recipient', 'n', '/rɪˈsɪpiənt/', 'người nhận thư/email', 'Ensure the recipient’s email address is spelled correctly before hitting send.'),
      w('attachment', 'n', '/əˈtætʃmənt/', 'tệp tin đính kèm trong email', 'The quarterly revenue spreadsheet is included as an attachment to this email.'),
      w('circulate', 'v', '/ˈsɜːkjəleɪt/', 'luân chuyển, gửi phổ biến cho toàn thể', 'The office manager circulated the holiday party invitation across all departments.'),
      w('classified', 'adj', '/ˈklæsɪfaɪd/', 'tuyệt mật, được bảo vệ nghiêm ngặt', 'All technical schematics and prototypes are marked as strictly classified.'),
      w('enclosure', 'n', '/ɪnˈkləʊʒə(r)/', 'tài liệu đính kèm phong bì thư giấy', 'Please sign and return the enclosed contract using the pre-paid envelope.'),
      w('compose', 'v', '/kəmˈpəʊz/', 'soạn thảo, viết thư thương mại', 'The executive secretary composed a tactful response to the upset business partner.'),
      w('notify', 'v', '/ˈnəʊtɪfaɪ/', 'thông báo chính thức cho ai biết', 'Tenants must notify building management at least thirty days before vacating.'),
      w('carbon copy', 'n phr', '/ˌkɑːbən ˈkɒpi/', 'gửi bản sao email cho người liên quan (CC)', 'Please carbon copy the project manager on all correspondence with the external client.'),
      w('blind copy', 'n phr', '/blaɪnd ˈkɒpi/', 'gửi bản sao ẩn danh (BCC)', 'Use blind copy when sending promotional newsletters to protect subscriber privacy.'),
      w('salutation', 'n', '/ˌsæljuˈteɪʃn/', 'lời chào mở đầu thư (Dear Mr. Smith)', 'A professional formal letter typically opens with a courteous salutation.'),
      w('complimentary close', 'n phr', '/ˌkɒmplɪˌmentri ˈkləʊz/', 'lời chào kết thư (Sincerely, Regards)', '"Sincerely yours" is a traditional complimentary close for business letters.'),
      w('bulletin', 'n', '/ˈbʊlətɪn/', 'bản tin nội bộ, thông báo nhanh', 'Check the company intranet bulletin board for announcements regarding office closures.'),
      w('newsletter', 'n', '/ˈnjuːzletə(r)/', 'bản tin định kỳ gửi khách/nhân viên', 'Our monthly corporate newsletter highlights employee achievements and upcoming events.'),
      w('promptly', 'adv', '/ˈprɒmptli/', 'ngay lập tức, không chậm trễ', 'We strive to answer all client emails promptly within two business hours.'),
      w('acknowledgment', 'n', '/əkˈnɒlɪdʒmənt/', 'thư xác nhận đã nhận được gì', 'The customer received an automated acknowledgment of their service request.'),
      w('concise', 'adj', '/kənˈsaɪs/', 'ngắn gọn, súc tích, rõ ý', 'Keep executive memos concise and focused strictly on actionable conclusions.'),
      w('formal', 'adj', '/ˈfɔːml/', 'trang trọng, đúng chuẩn mực nghi thức', 'Business email communications should maintain a professional and formal tone.'),
      w('forward', 'v', '/ˈfɔːwəd/', 'chuyển tiếp thư/email cho người khác', 'Could you please forward the invoice approval thread to the accounting team?'),
      w('clarify', 'v', '/ˈklærəfaɪ/', 'làm rõ, giải thích rõ ràng hơn', 'The supervisor sent a follow-up email to clarify the updated overtime guidelines.'),
      w('subject line', 'n phr', '/ˈsʌbdʒɪkt laɪn/', 'dòng tiêu đề của thư điện tử', 'Write a clear, descriptive subject line so recipients recognize the email’s importance.'),
      w('courteous', 'adj', '/ˈkɜːtiəs/', 'lịch thiệp, nhã nhặn trong giao tiếp', 'Customer service emails should always begin with a warm and courteous greeting.'),
      w('reiterate', 'v', '/riˈɪtəreɪt/', 'nhắc lại, nhấn mạnh lại lần nữa', 'The CEO reiterated the company’s zero-tolerance policy against workplace harassment.'),
      w('transmit', 'v', '/trænzˈmɪt/', 'truyền phát, gửi đi qua đường điện tử', 'Confidential financial spreadsheets were transmitted via encrypted file transfer.'),
      w('urgent', 'adj', '/ˈɜːdʒənt/', 'khẩn cấp, cần giải quyết gấp', 'Flag emails as urgent only when immediate operational action is required.'),
      w('proofread', 'v', '/ˈpruːfriːd/', 'đọc soát lỗi chính tả trước khi gửi', 'Always proofread critical executive reports for grammatical typos before distribution.'),
      w('addressee', 'n', '/ˌædreˈsiː/', 'người được gửi tới theo địa chỉ', 'If you are not the intended addressee of this confidential email, please delete it.'),
      w('follow-up', 'n, adj', '/ˈfɒləʊ ʌp/', 'thư/cuộc gọi tiếp nối sau cuộc họp', 'The sales rep sent a friendly follow-up email thanking the client for their time.')
    ]
  },
  {
    id: 22,
    title: 'Bán lẻ, Siêu thị & Thương mại điện tử (Retail, Supermarkets & E-Commerce)',
    words: [
      w('wares', 'n (pl)', '/weəz/', 'hàng hóa bày bán ngoài chợ/cửa hàng', 'Artisans displayed their handmade ceramic wares at the weekend open market.'),
      w('stocktaking', 'n', '/ˈstɒkteɪkɪŋ/', 'công tác kiểm kê hàng tồn kho thực tế', 'The retail store closes early on the last Sunday of each quarter for stocktaking.'),
      w('clearance sale', 'n phr', '/ˈklɪərəns seɪl/', 'đợt xả kho thanh lý hàng tồn', 'Clothing stores hold clearance sales at the end of each season to make room for new stock.'),
      w('checkout', 'n', '/ˈtʃekaʊt/', 'quầy thu ngân, quy trình thanh toán', 'Self-service checkouts help shoppers scan and pay for groceries rapidly.'),
      w('shopping cart', 'n phr', '/ˈʃɒpɪŋ kɑːt/', 'giỏ hàng mua sắm (trực tiếp hoặc online)', 'Online shoppers frequently abandon their shopping carts before completing payment.'),
      w('aisle', 'n', '/aɪl/', 'lối đi giữa các quầy kệ hàng siêu thị', 'Canned vegetables and soups are located in aisle 4 on the left.'),
      w('discount', 'n, v', '/ˈdɪskaʊnt/', 'chiết khấu, giảm giá; bớt giá', 'Subscribers receive a 15% promotional discount on their first online order.'),
      w('voucher', 'n', '/ˈvaʊtʃə(r)/', 'phiếu giảm giá, phiếu mua hàng quà tặng', 'Shoppers redeemed gift vouchers worth $50 during the holiday shopping rush.'),
      w('loyalty program', 'n phr', '/ˈlɔɪəlti ˈprəʊɡræm/', 'chương trình khách hàng thân thiết tích điểm', 'Our loyalty program rewards frequent shoppers with redeemable reward points.'),
      w('store credit', 'n phr', '/stɔː ˈkredɪt/', 'tiền hoàn lại dạng điểm mua sắm tại quầy', 'Shoppers returning clothes without receipts are offered store credit.'),
      w('exchange', 'v, n', '/ɪksˈtʃeɪndʒ/', 'đổi trả hàng lấy món khác', 'Customers can exchange unworn shoes for a different size at any retail branch.'),
      w('display', 'n, v', '/dɪˈspleɪ/', 'sự trưng bày tủ kính; bày biện hàng', 'The window display showcases the latest autumn fashion collection.'),
      w('shelf life', 'n phr', '/ʃelf laɪf/', 'hạn sử dụng của sản phẩm', 'Pasteurized milk has a limited refrigerated shelf life of approximately two weeks.'),
      w('e-commerce', 'n', '/ˈiː kɒmɜːs/', 'thương mại điện tử bán hàng online', 'E-commerce transactions now account for over a quarter of total retail volume.'),
      w('retailer', 'n', '/ˈriːteɪlə(r)/', 'nhà bán lẻ, người bán buôn nhỏ', 'The nationwide retailer operates more than 400 department stores across the continent.'),
      w('point of sale (POS)', 'n phr', '/pɔɪnt əv seɪl/', 'điểm bán hàng, máy thanh toán POS', 'Modern point of sale terminals accept contactless credit cards and mobile wallets.'),
      w('bargain', 'n, v', '/ˈbɑːɡən/', 'món hời, giá rẻ; mặc cả trả giá', 'Shoppers found exceptional bargains at the weekend open-air flea market.'),
      w('overstocked', 'adj', '/ˌəʊvəˈstɒkt/', 'tồn đọng quá nhiều hàng ế', 'The electronics retailer was heavily overstocked on last year’s television models.'),
      w('sold out', 'adj phr', '/səʊld aʊt/', 'đã bán sạch hết hàng', 'Concert tickets and commemorative T-shirts were completely sold out within minutes.'),
      w('restock', 'v', '/ˌriːˈstɒk/', 'châm thêm hàng lên kệ, nhập bổ sung', 'Store clerks restock supermarket shelves overnight to prepare for morning crowds.'),
      w('bulk discount', 'n phr', '/bʌlk ˈdɪskaʊnt/', 'giảm giá khi mua số lượng sỉ', 'Warehouse clubs offer steep bulk discounts to customers purchasing family packs.'),
      w('cashier', 'n', '/kæˈʃɪə(r)/', 'nhân viên thu ngân tính tiền', 'The friendly cashier handed the shopper their change and itemized receipt.'),
      w('drop-shipping', 'n', '/ˈdrɒp ʃɪpɪŋ/', 'mô hình bán hàng không cần giữ kho', 'Many online entrepreneurs use drop-shipping to sell goods manufactured abroad.'),
      w('order fulfillment', 'n phr', '/ˈɔːdə fʊlˈfɪlmənt/', 'hoàn tất đóng gói và giao đơn hàng', 'Automated robotic warehouses speed up order fulfillment during the Christmas rush.'),
      w('promotional', 'adj', '/prəˈməʊʃənl/', 'mang tính khuyến mãi, quảng cáo', 'Staff handed out promotional product samples to passersby outside the boutique.'),
      w('brick-and-mortar', 'adj', '/ˌbrɪk ənd ˈmɔːtə(r)/', 'cửa hàng truyền thống có mặt bằng thực tế', 'Traditional brick-and-mortar retailers must adapt to survive in the digital age.'),
      w('consumer goods', 'n phr', '/kənˈsjuːmə ɡʊdz/', 'hàng tiêu dùng nhanh thường nhật', 'The multinational giant manufactures popular packaged consumer goods and toiletries.'),
      w('price match', 'n, v', '/praɪs mætʃ/', 'chính sách cam kết bán bằng giá đối thủ', 'The store will price match any lower verified price advertised by local competitors.'),
      w('markup', 'n', '/ˈmɑːkʌp/', 'mức chênh lệch tăng giá bán so với giá vốn', 'Luxury boutique brands often apply a 300% markup to imported designer apparel.'),
      w('window shopping', 'n phr', '/ˈwɪndəʊ ˈʃɒpɪŋ/', 'đi ngắm hàng qua tủ kính (chưa mua)', 'On lazy Sunday afternoons, thousands of tourists enjoy window shopping along Fifth Avenue.')
    ]
  }
];
