import { w } from './helper.js';

export const unitsPart1 = [
  {
    id: 1,
    title: 'Hợp đồng, Đàm phán & Pháp lý (Contracts & Legal)',
    words: [
      w('abide by', 'phr v', '/əˈbaɪd baɪ/', 'tuân theo, chịu theo (thỏa thuận, quy tắc)', 'Both parties agreed to abide by the terms of the contract.'),
      w('agreement', 'n', '/əˈɡriːmənt/', 'hợp đồng, sự thỏa thuận, hiệp định', 'The signed agreement will take effect starting next Monday.'),
      w('assurance', 'n', '/əˈʃʊərəns/', 'sự bảo đảm, sự cam đoan', 'The sales director gave his assurance that delivery would be on time.'),
      w('cancellation', 'n', '/ˌkænsəˈleɪʃn/', 'sự hủy bỏ, bãi bỏ hợp đồng', 'The contract includes a cancellation clause with a 30-day notice.'),
      w('determine', 'v', '/dɪˈtɜːmɪn/', 'xác định, quyết định', 'Market research will determine whether we launch the product.'),
      w('engage', 'v', '/ɪnˈɡeɪdʒ/', 'tham gia vào, thuê mướn (dịch vụ chuyên gia)', 'We need to engage an outside legal consultant for this merger.'),
      w('establish', 'v', '/ɪˈstæblɪʃ/', 'thành lập, thiết lập quan hệ', 'The firm has established a strong reputation for reliability.'),
      w('obligate', 'v', '/ˈɒblɪɡeɪt/', 'bắt buộc, ép buộc về mặt pháp lý', 'The contractor is obligated to complete the project by December.'),
      w('party', 'n', '/ˈpɑːti/', 'bên tham gia ký kết hợp đồng', 'Both parties must sign the non-disclosure agreement.'),
      w('provision', 'n', '/prəˈvɪʒn/', 'điều khoản (hợp đồng), sự cung cấp', 'Carefully read the provisions regarding warranty and refunds.'),
      w('resolve', 'v', '/rɪˈzɒlv/', 'giải quyết (tranh chấp, mâu thuẫn)', 'Management hopes to resolve the dispute out of court.'),
      w('specific', 'adj', '/spəˈsɪfɪk/', 'cụ thể, chi tiết, đặc trưng', 'The contract specifies the exact delivery dates and locations.'),
      w('stipulate', 'v', '/ˈstɪpjuleɪt/', 'quy định rõ ràng, đặt điều kiện', 'The policy stipulates that travel expenses must be pre-approved.'),
      w('binding', 'adj', '/ˈbaɪndɪŋ/', 'ràng buộc pháp lý', 'This agreement is legally binding once signed by both executives.'),
      w('clause', 'n', '/klɔːz/', 'điều khoản trong văn bản luật/hợp đồng', 'The confidentiality clause remains valid for three years.'),
      w('breach', 'n, v', '/briːtʃ/', 'vi phạm hợp đồng, sự phá vỡ cam kết', 'Failing to deliver goods on time constitutes a breach of contract.'),
      w('comply with', 'phr v', '/kəmˈplaɪ wɪð/', 'tuân thủ theo (quy định, tiêu chuẩn)', 'All suppliers must comply with international safety regulations.'),
      w('negotiate', 'v', '/nɪˈɡəʊʃieɪt/', 'đàm phán, thương lượng điều khoản', 'The procurement team negotiated a 15% discount on bulk orders.'),
      w('counterpart', 'n', '/ˈkaʊntəpɑːt/', 'đối tác đàm phán tương đương', 'Our CEO met with his Japanese counterpart in Tokyo.'),
      w('null and void', 'idiom', '/nʌl ənd vɔɪd/', 'vô hiệu lực, không còn giá trị pháp lý', 'If the deposit is not received by Friday, the contract is null and void.'),
      w('indemnify', 'v', '/ɪnˈdemnɪfaɪ/', 'bồi thường thiệt hại, bồi hoàn', 'The supplier agreed to indemnify the buyer against any patent claims.'),
      w('liable', 'adj', '/ˈlaɪəbl/', 'chịu trách nhiệm pháp lý', 'The tenant is liable for any damage caused to the property.'),
      w('settlement', 'n', '/ˈsetlmənt/', 'sự dàn xếp, sự giải quyết ổn thỏa', 'The two corporations reached a multi-million-dollar settlement.'),
      w('draft', 'v, n', '/drɑːft/', 'soạn thảo; bản thảo hợp đồng', 'The legal team is drafting the final version of the commercial lease.'),
      w('amend', 'v', '/əˈmend/', 'sửa đổi, bổ sung (hợp đồng, luật)', 'The committee voted to amend the corporate bylaws.'),
      w('covenant', 'n, v', '/ˈkʌvənənt/', 'giao ước, cam ước hợp đồng', 'The tenant entered into a covenant not to sublet the apartment.'),
      w('terminate', 'v', '/ˈtɜːmɪneɪt/', 'chấm dứt, kết thúc (hợp đồng, dự án)', 'Either party may terminate the contract with two weeks’ written notice.'),
      w('waive', 'v', '/weɪv/', 'từ bỏ (quyền lợi), miễn (phí)', 'The bank agreed to waive the late payment penalty fee.'),
      w('arbitration', 'n', '/ˌɑːbɪˈtreɪʃn/', 'sự phân xử, trọng tài thương mại', 'Disputes will be resolved through binding international arbitration.'),
      w('validity', 'n', '/vəˈlɪdəti/', 'giá trị pháp lý, tính hiệu lực', 'The lawyer questioned the legal validity of the unsigned document.')
    ]
  },
  {
    id: 2,
    title: 'Tiếp thị, Bán hàng & Nghiên cứu thị trường (Marketing & Sales)',
    words: [
      w('attract', 'v', '/əˈtrækt/', 'thu hút, lôi cuốn khách hàng', 'The annual trade expo attracted over 5,000 industry professionals.'),
      w('compare', 'v', '/kəmˈpeə(r)/', 'so sánh, đối chiếu giá cả/chất lượng', 'Consumers frequently compare prices online before purchasing.'),
      w('competition', 'n', '/ˌkɒmpəˈtɪʃn/', 'sự cạnh tranh, đối thủ cạnh tranh', 'Intense competition forced the company to lower its retail prices.'),
      w('consume', 'v', '/kənˈsjuːm/', 'tiêu thụ, tiêu dùng', 'Vehicles that consume less fuel have become increasingly popular.'),
      w('convince', 'v', '/kənˈvɪns/', 'thuyết phục khách hàng/nhà đầu tư', 'The sales presentation convinced the board to expand the budget.'),
      w('currently', 'adv', '/ˈkʌrəntli/', 'hiện tại, hiện nay', 'We are currently developing a new line of organic skincare products.'),
      w('fad', 'n', '/fæd/', 'mốt nhất thời, xu hướng ngắn hạn', 'The product was dismissed as a passing fad, but sales stayed robust.'),
      w('inspiration', 'n', '/ˌɪnspəˈreɪʃn/', 'nguồn cảm hứng, sáng kiến thiết kế', 'Customer feedback served as the primary inspiration for the redesign.'),
      w('market', 'v, n', '/ˈmɑːkɪt/', 'tiếp thị, tung ra thị trường; thị trường', 'The agency knows how to market luxury items to younger demographics.'),
      w('persuasion', 'n', '/pəˈsweɪʒn/', 'sức thuyết phục, tài thuyết phục', 'Effective advertising relies heavily on subtle emotional persuasion.'),
      w('productive', 'adj', '/prəˈdʌktɪv/', 'năng suất, hiệu quả', 'Our creative team had a very productive brainstorming session.'),
      w('satisfaction', 'n', '/ˌsætɪsˈfækʃn/', 'sự thỏa mãn, mức độ hài lòng khách hàng', 'The annual survey revealed a 95% customer satisfaction rating.'),
      w('endorsement', 'n', '/ɪnˈdɔːsmənt/', 'sự chứng thực, quảng bá của người nổi tiếng', 'Celebrity endorsements significantly boosted quarterly cosmetics sales.'),
      w('campaign', 'n', '/kæmˈpeɪn/', 'chiến dịch quảng cáo/tiếp thị', 'The digital marketing campaign will run across all social networks.'),
      w('demographic', 'n, adj', '/ˌdeməˈɡræfɪk/', 'nhóm nhân khẩu học, nhóm khách hàng mục tiêu', 'Our core demographic consists of urban professionals aged 25–40.'),
      w('launch', 'v, n', '/lɔːntʃ/', 'ra mắt, giới thiệu sản phẩm mới', 'The company plans to launch the flagship smartphone next spring.'),
      w('brand loyalty', 'n phr', '/brænd ˈlɔɪəlti/', 'lòng trung thành với thương hiệu', 'Exceptional after-sales support is key to building lasting brand loyalty.'),
      w('niche', 'n, adj', '/niːʃ/', 'thị trường ngách, thích hợp', 'The startup successfully carved out a profitable niche market.'),
      w('flyer', 'n', '/ˈflaɪə(r)/', 'tờ rơi quảng cáo', 'Staff distributed promotional flyers outside the convention center.'),
      w('promising', 'adj', '/ˈprɒmɪsɪŋ/', 'đầy triển vọng, hứa hẹn', 'Early sales figures in the European region look very promising.'),
      w('penetrate', 'v', '/ˈpenətreɪt/', 'thâm nhập vào thị trường mới', 'The beverage manufacturer is striving to penetrate emerging markets.'),
      w('rebate', 'n', '/ˈriːbeɪt/', 'khoản giảm giá hoàn lại tiền', 'Customers can claim a $50 mail-in rebate with their proof of purchase.'),
      w('commercial', 'n, adj', '/kəˈmɜːʃl/', 'quảng cáo truyền hình/radio; thuộc thương mại', 'The television commercial was broadcast during prime-time evening hours.'),
      w('sponsor', 'v, n', '/ˈspɒnsə(r)/', 'tài trợ; nhà tài trợ', 'Tech giant Microsoft agreed to sponsor the international robotics summit.'),
      w('potential', 'adj, n', '/pəˈtenʃl/', 'tiềm năng, triển vọng', 'The workshop aims to turn prospective leads into paying clients.'),
      w('turnout', 'n', '/ˈtɜːnaʊt/', 'số người tham dự sự kiện', 'There was a surprisingly large turnout at the product showcase.'),
      w('retail', 'n, v', '/ˈriːteɪl/', 'bán lẻ', 'The suggested retail price for the tablet is $299.'),
      w('wholesale', 'n, adv', '/ˈhəʊlseɪl/', 'bán buôn, bán sỉ', 'Wholesale distributors receive bulk discounts of up to 40%.'),
      w('merchandise', 'n', '/ˈmɜːtʃəndaɪz/', 'hàng hóa thương mại', 'Defective merchandise must be returned within 14 business days.'),
      w('word-of-mouth', 'adj, n', '/ˌwɜːd əv ˈmaʊθ/', 'truyền miệng (quảng cáo không tốn phí)', 'Word-of-mouth recommendations drove our restaurant’s early success.')
    ]
  },
  {
    id: 3,
    title: 'Tài chính, Kế toán & Thuế (Finance, Accounting & Taxes)',
    words: [
      w('accumulate', 'v', '/əˈkjuːmjəleɪt/', 'tích lũy, dồn lại qua thời gian', 'The company accumulated substantial debt during rapid expansion.'),
      w('asset', 'n', '/ˈæset/', 'tài sản của cá nhân/doanh nghiệp', 'Equipment and real estate make up the bulk of our tangible assets.'),
      w('audit', 'n, v', '/ˈɔːdɪt/', 'kiểm toán, sự thanh tra sổ sách kế toán', 'An independent auditor will inspect our accounting records next month.'),
      w('budget', 'n, v', '/ˈbʌdʒɪt/', 'ngân sách; lên ngân sách dự toán', 'We must keep operating expenses strictly within the approved budget.'),
      w('build up', 'phr v', '/bɪld ʌp/', 'xây dựng dần dần, tích tụ', 'It takes years of discipline to build up a substantial emergency fund.'),
      w('debt', 'n', '/det/', 'khoản nợ, dư nợ', 'The restructuring plan helps the corporation pay off its long-term debt.'),
      w('outstanding', 'adj', '/aʊtˈstændɪŋ/', 'chưa thanh toán, còn nợ; xuất sắc', 'Please settle all outstanding invoices before the billing cycle closes.'),
      w('profitable', 'adj', '/ˈprɒfɪtəbl/', 'sinh lời, có lợi nhuận', 'The renewable energy division finally became profitable this quarter.'),
      w('reconcile', 'v', '/ˈrekənsaɪl/', 'đối chiếu, làm khớp số liệu sổ sách', 'The accountant spent days reconciling the bank statements with receipts.'),
      w('turnover', 'n', '/ˈtɜːnəʊvə(r)/', 'doanh số, doanh thu tổng', 'Annual turnover increased by 18% thanks to expanding overseas exports.'),
      w('dividend', 'n', '/ˈdɪvɪdend/', 'cổ tức chi trả cho cổ đông', 'Shareholders will receive a quarterly dividend of $1.25 per share.'),
      w('fiscal year', 'n phr', '/ˈfɪskl jɪə(r)/', 'năm tài chính, tài khóa', 'The budget for fiscal year 2026 will be presented to the board today.'),
      w('deduct', 'v', '/dɪˈdʌkt/', 'khấu trừ, trừ bớt (thuế, chi phí)', 'Charitable contributions can be deducted from taxable corporate income.'),
      w('exempt', 'adj, v', '/ɪɡˈzempt/', 'được miễn trừ (thuế, nghĩa vụ)', 'Certain essential medical supplies are completely exempt from import duties.'),
      w('expenditure', 'n', '/ɪkˈspendɪtʃə(r)/', 'khoản chi tiêu, chi phí bỏ ra', 'Capital expenditure on automated machinery rose significantly this year.'),
      w('ledger', 'n', '/ˈledʒə(r)/', 'sổ cái kế toán', 'All transactions must be accurately recorded in the general ledger.'),
      w('liability', 'n', '/ˌlaɪəˈbɪləti/', 'khoản nợ phải trả, nghĩa vụ tài chính', 'The company’s current liabilities exceed its liquid assets.'),
      w('revenue', 'n', '/ˈrevənjuː/', 'doanh thu từ bán hàng/dịch vụ', 'Advertising revenue declined sharply during the economic downturn.'),
      w('deficit', 'n', '/ˈdefɪsɪt/', 'thâm hụt ngân sách, số tiền thiếu hụt', 'The government is taking bold measures to reduce the trade deficit.'),
      w('surplus', 'n, adj', '/ˈsɜːpləs/', 'thặng dư, số dư thừa', 'The budget surplus will be allocated to infrastructure projects.'),
      w('depreciation', 'n', '/dɪˌpriːʃiˈeɪʃn/', 'khấu hao tài sản cố định', 'The accountant calculated depreciation on the company vehicles.'),
      w('overhead', 'n, adj', '/ˈəʊvəhed/', 'chi phí vận hành gián tiếp', 'Switching to remote work helped reduce office overhead costs.'),
      w('solvent', 'adj', '/ˈsɒlvənt/', 'có khả năng thanh toán nợ', 'Despite market volatility, the corporation remains entirely solvent.'),
      w('insolvency', 'n', '/ɪnˈsɒlvənsi/', 'tình trạng vỡ nợ, mất khả năng thanh toán', 'The retail chain filed for protection following months of insolvency.'),
      w('yield', 'n, v', '/jiːld/', 'lợi tức, tỷ suất sinh lời; mang lại lợi nhuận', 'Treasury bonds offer a steady and predictable annual yield.'),
      w('statement', 'n', '/ˈsteɪtmənt/', 'sao kê tài khoản, báo cáo tài chính', 'Please review your monthly credit card statement for unauthorized charges.'),
      w('discrepancy', 'n', '/dɪˈskrepənsi/', 'sự chênh lệch, sự không khớp số liệu', 'Auditors discovered an unexplained discrepancy in the petty cash log.'),
      w('portfolio', 'n', '/pɔːtˈfəʊliəʊ/', 'danh mục đầu tư tài chính', 'Financial advisors recommend diversifying your investment portfolio.'),
      w('liquidity', 'n', '/lɪˈkwɪdəti/', 'tính thanh khoản (khả năng đổi ra tiền mặt)', 'Maintaining sufficient liquidity is crucial during financial crises.'),
      w('reimburse', 'v', '/ˌriːɪmˈbɜːs/', 'hoàn tiền, bồi hoàn chi phí công tác', 'The accounting department will reimburse your travel expenses next week.')
    ]
  },
  {
    id: 4,
    title: 'Quản trị doanh nghiệp & Họp HĐQT (Corporate Strategy & Board Governance)',
    words: [
      w('board of directors', 'n phr', '/bɔːd əv dəˈrektəz/', 'hội đồng quản trị', 'The board of directors approved the acquisition proposal yesterday.'),
      w('executive', 'n, adj', '/ɪɡˈzekjətɪv/', 'giám đốc điều hành; thuộc cấp quản lý cao cấp', 'Senior executives held an emergency summit regarding market volatility.'),
      w('chairperson', 'n', '/ˈtʃeəpɜːsn/', 'chủ tịch hội đồng quản trị/cuộc họp', 'The chairperson called the annual general meeting to order promptly at 9 AM.'),
      w('agenda', 'n', '/əˈdʒendə/', 'chương trình nghị sự, nội dung cuộc họp', 'The first item on the agenda is the review of Q3 earnings.'),
      w('adjourn', 'v', '/əˈdʒɜːn/', 'hoãn, tạm ngưng cuộc họp', 'The board voted to adjourn the meeting until Thursday afternoon.'),
      w('merger', 'n', '/ˈmɜːdʒə(r)/', 'sự sáp nhập doanh nghiệp', 'The merger between the two airline carriers created an industry giant.'),
      w('acquisition', 'n', '/ˌækwɪˈzɪʃn/', 'sự mua lại công ty khác, thâu tóm', 'The tech firm announced the acquisition of a promising AI startup.'),
      w('subsidiary', 'n', '/səbˈsɪdiəri/', 'công ty con', 'The multinational operates several subsidiaries across Southeast Asia.'),
      w('implement', 'v', '/ˈɪmplɪment/', 'thi hành, thực hiện (chiến lược, chính sách)', 'Management will implement a new performance evaluation system next month.'),
      w('initiative', 'n', '/ɪˈnɪʃətɪv/', 'sáng kiến, kế hoạch hành động mới', 'The green energy initiative aims to reduce carbon emissions by 40%.'),
      w('objective', 'n', '/əbˈdʒektɪv/', 'mục tiêu chiến lược cần đạt được', 'Our primary objective for this fiscal year is expanding market share.'),
      w('restructure', 'v', '/ˌriːˈstrʌktʃə(r)/', 'tái cơ cấu tổ chức doanh nghiệp', 'The conglomerate restructured its operations to cut unnecessary costs.'),
      w('stakeholder', 'n', '/ˈsteɪkhəʊldə(r)/', 'các bên liên quan (cổ đông, nhân viên, đối tác)', 'We must consider the concerns of all key stakeholders before voting.'),
      w('quorum', 'n', '/ˈkwɔːrəm/', 'số lượng đại biểu tối thiểu để biểu quyết', 'A quorum was reached, allowing the committee to vote on the resolution.'),
      w('minutes', 'n (pl)', '/ˈmɪnɪts/', 'biên bản cuộc họp', 'The corporate secretary circulated the official meeting minutes by email.'),
      w('conglomerate', 'n', '/kənˈɡlɒmərət/', 'tập đoàn đa ngành khổng lồ', 'The Korean conglomerate operates in electronics, shipbuilding, and finance.'),
      w('shareholder', 'n', '/ˈʃeəhəʊldə(r)/', 'cổ đông công ty', 'Shareholders demanded greater transparency regarding executive bonuses.'),
      w('unanimous', 'adj', '/juˈnænɪməs/', 'nhất trí, toàn thể đồng ý', 'The board reached a unanimous decision to appoint Mr. Lee as CEO.'),
      w('proxy', 'n', '/ˈprɒksi/', 'người được ủy quyền, giấy ủy quyền biểu quyết', 'Investors unable to attend the summit may vote by proxy.'),
      w('strategic', 'adj', '/strəˈtiːdʒɪk/', 'mang tính chiến lược dài hạn', 'Forming an alliance with our rival was a bold strategic move.'),
      w('supervise', 'v', '/ˈsuːpəvaɪz/', 'giám sát, chỉ đạo cấp dưới', 'The operations manager supervises a team of 40 field technicians.'),
      w('delegate', 'v, n', '/ˈdelɪɡeɪt/', 'giao phó quyền hạn; đại biểu tham dự', 'Effective leaders know how to delegate critical tasks to capable deputies.'),
      w('consolidation', 'n', '/kənˌsɒlɪˈdeɪʃn/', 'sự hợp nhất, củng cố vị thế', 'The consolidation of our regional warehouses will streamline distribution.'),
      w('takeover', 'n', '/ˈteɪkəʊvə(r)/', 'sự tiếp quản công ty, thôn tính', 'The board rejected the hostile takeover bid from an overseas hedge fund.'),
      w('vision', 'n', '/ˈvɪʒn/', 'tầm nhìn định hướng tương lai', 'The founder shared his visionary roadmap for the next decade of innovation.'),
      w('benchmark', 'n, v', '/ˈbentʃmɑːk/', 'tiêu chuẩn đối chuẩn; lấy làm thước đo', 'Our delivery speed sets the industry benchmark for e-commerce.'),
      w('convene', 'v', '/kənˈviːn/', 'triệu tập cuộc họp, nhóm họp', 'The committee will convene next Tuesday to review the audit results.'),
      w('resolution', 'n', '/ˌrezəˈluːʃn/', 'nghị quyết thông qua sau biểu quyết', 'The board passed a resolution approving the issuance of corporate bonds.'),
      w('veto', 'v, n', '/ˈviːtəʊ/', 'phủ quyết; quyền phủ quyết', 'The managing director has the power to veto any major capital expense.'),
      w('corporate governance', 'n phr', '/ˈkɔːpərət ˈɡʌvənəns/', 'quản trị công ty, cơ chế điều hành minh bạch', 'Good corporate governance protects minority investors and builds public trust.')
    ]
  },
  {
    id: 5,
    title: 'Nhân sự, Tuyển dụng & Đào tạo (HR, Recruitment & Training)',
    words: [
      w('applicant', 'n', '/ˈæplɪkənt/', 'ứng viên nộp đơn xin việc', 'More than two hundred applicants applied for the junior developer role.'),
      w('candidate', 'n', '/ˈkændɪdət/', 'ứng cử viên sáng giá', 'The search committee interviewed four highly qualified candidates.'),
      w('hire', 'v, n', '/ˈhaɪə(r)/', 'tuyển dụng, thuê; nhân viên mới tuyển', 'The engineering department plans to hire six software engineers this quarter.'),
      w('recruit', 'v, n', '/rɪˈkruːt/', 'chiêu mộ, tuyển mộ nhân tài; lính mới', 'Our HR team recruits promising graduates directly from top universities.'),
      w('resume', 'n', '/ˈrezjuːmeɪ/', 'sơ yếu lý lịch xin việc', 'Please submit your resume along with two professional references.'),
      w('qualification', 'n', '/ˌkwɒlɪfɪˈkeɪʃn/', 'bằng cấp, năng lực chuyên môn đạt chuẩn', 'A master’s degree in finance is a mandatory qualification for this post.'),
      w('interview', 'n, v', '/ˈɪntəvjuː/', 'buổi phỏng vấn; phỏng vấn xin việc', 'Second-round interviews will be conducted via video conference on Friday.'),
      w('probation', 'n', '/prəˈbeɪʃn/', 'thời gian thử việc', 'New hires must successfully complete a three-month probation period.'),
      w('onboard', 'v', '/ˈɒnbɔːd/', 'tiếp nhận và hướng dẫn nhân viên mới', 'The HR department onboarded twenty new customer support agents today.'),
      w('orientation', 'n', '/ˌɔːriənˈteɪʃn/', 'buổi định hướng hội nhập', 'Mandatory safety orientation begins promptly at 8:30 AM tomorrow.'),
      w('headhunter', 'n', '/ˈhedhʌntə(r)/', 'chuyên viên săn đầu người cấp cao', 'The firm engaged an executive headhunter to locate a new Chief Financial Officer.'),
      w('personnel', 'n', '/ˌpɜːsəˈnel/', 'nhân sự, toàn thể cán bộ nhân viên', 'All sales personnel are required to attend the quarterly workshop.'),
      w('job description', 'n phr', '/dʒɒb dɪˈskrɪpʃn/', 'bản mô tả công việc', 'The job description outlines core responsibilities and required credentials.'),
      w('vacancy', 'n', '/ˈveɪkənsi/', 'vị trí việc làm còn trống', 'Due to recent promotions, our accounting team has an immediate vacancy.'),
      w('eligible', 'adj', '/ˈelɪdʒəbl/', 'đủ tư cách, đáp ứng đủ tiêu chuẩn', 'Only full-time employees are eligible for the corporate health plan.'),
      w('credential', 'n', '/krəˈdenʃl/', 'chứng chỉ chuyên môn, bằng cấp xác thực', 'Auditors verified the credentials of all contracted civil engineers.'),
      w('mentor', 'n, v', '/ˈmentɔː(r)/', 'người hướng dẫn dày dạn; hướng dẫn kèm cặp', 'Senior analysts mentor newcomers throughout their first year.'),
      w('apprentice', 'n', '/əˈprentɪs/', 'người học việc, thực tập sinh nghề', 'The technical academy places apprentices at local manufacturing plants.'),
      w('shortlist', 'v, n', '/ˈʃɔːtlɪst/', 'chọn vào danh sách sơ tuyển hẹp', 'The hiring panel shortlisted five contenders for the final interview.'),
      w('attrition', 'n', '/əˈtrɪʃn/', 'sự hao hụt nhân sự tự nhiên (nghỉ hưu, chuyển việc)', 'The company reduced employee attrition by introducing flexible hybrid schedules.'),
      w('reference', 'n', '/ˈrefrəns/', 'thư giới thiệu, người bảo lãnh chuyên môn', 'The recruiter checked references provided by former supervisors.'),
      w('cover letter', 'n phr', '/ˈkʌvə letə(r)/', 'thư xin việc, thư ngỏ ứng tuyển', 'Attach a customized cover letter highlighting your project management experience.'),
      w('competence', 'n', '/ˈkɒmpɪtəns/', 'năng lực, sự thành thạo công việc', 'Candidates must demonstrate proven competence in database administration.'),
      w('turnover rate', 'n phr', '/ˈtɜːnəʊvə reɪt/', 'tỷ lệ luân chuyển nhân sự nghỉ việc', 'Competitive compensation packages keep our employee turnover rate remarkably low.'),
      w('screening', 'n', '/ˈskriːnɪŋ/', 'vòng thẩm tra hồ sơ sơ bộ', 'Initial resume screening eliminated candidates without bilingual proficiency.'),
      w('hiree', 'n', '/haɪəˈriː/', 'người vừa được tuyển dụng', 'Each new hiree is paired with an experienced buddy for two months.'),
      w('background check', 'n phr', '/ˈbækɡraʊnd tʃek/', 'xác minh lý lịch tư pháp/học vấn', 'All prospective bank tellers must pass a comprehensive background check.'),
      w('aptitude', 'n', '/ˈæptɪtjuːd/', 'năng khiếu, khả năng tiếp thu nhanh', 'The technical assessment tests aptitude for algorithmic problem-solving.'),
      w('qualified', 'adj', '/ˈkwɒlɪfaɪd/', 'đủ năng lực chuyên môn, đạt tiêu chuẩn', 'We are actively seeking qualified individuals with healthcare management expertise.'),
      w('internship', 'n', '/ˈɪntɜːnʃɪp/', 'kỳ thực tập sinh', 'Summer internships offer students hands-on exposure to corporate finance.')
    ]
  },
  {
    id: 6,
    title: 'Lương bổng, Chế độ đãi ngộ & Phúc lợi (Salaries, Benefits & Perks)',
    words: [
      w('compensation', 'n', '/ˌkɒmpenˈseɪʃn/', 'thù lao tổng thể, sự bồi thường đãi ngộ', 'The executive compensation package includes stock options and bonus incentives.'),
      w('remuneration', 'n', '/rɪˌmjuːnəˈreɪʃn/', 'tiền thù lao, tiền công chi trả', 'Remuneration is commensurate with relevant corporate experience and skills.'),
      w('salary', 'n', '/ˈsæləri/', 'tiền lương tháng/năm cố định', 'Salaries are reviewed annually based on individual performance evaluations.'),
      w('wage', 'n', '/weɪdʒ/', 'tiền công nhật/tiền công theo giờ', 'The city voted to raise the legal minimum wage to $18 per hour.'),
      w('payroll', 'n', '/ˈpeɪrəʊl/', 'bảng lương, tổng quỹ lương công ty', 'Over 500 contract workers were recently added to the corporate payroll.'),
      w('benefit', 'n', '/ˈbenɪfɪt/', 'phúc lợi ngoài lương (y tế, bảo hiểm)', 'Health insurance and dental care are part of the standard benefit package.'),
      w('perk', 'n', '/pɜːk/', 'đặc quyền đãi ngộ (xe đưa đón, gym, ăn trưa)', 'Free gourmet meals and gym memberships are attractive tech company perks.'),
      w('pension', 'n', '/ˈpenʃn/', 'lương hưu, quỹ hưu trí', 'Employees contribute 5% of their monthly income to the retirement pension.'),
      w('stipend', 'n', '/ˈstaɪpend/', 'phụ cấp công tác, trợ cấp học tập', 'Interns receive a monthly housing stipend of $800 to cover urban living costs.'),
      w('severance pay', 'n phr', '/ˈsevərəns peɪ/', 'tiền trợ cấp thôi việc', 'Laid-off workers received three months’ severance pay and career transition support.'),
      w('appraisal', 'n', '/əˈpreɪzl/', 'sự đánh giá năng lực hoàn thành công việc', 'Annual performance appraisals determine year-end merit pay increases.'),
      w('merit increase', 'n phr', '/ˈmerɪt ˈɪnkriːs/', 'tăng lương theo thành tích xuất sắc', 'Top-performing account executives received a 10% merit increase.'),
      w('cost of living', 'n phr', '/kɒst əv ˈlɪvɪŋ/', 'chi phí sinh hoạt đắt đỏ', 'The union negotiated a cost-of-living allowance to offset rising inflation.'),
      w('overtime', 'n, adv', '/ˈəʊvətaɪm/', 'tiền làm thêm giờ; làm ngoài giờ', 'Factory personnel who work weekend shifts receive double overtime wages.'),
      w('bonus', 'n', '/ˈbəʊnəs/', 'tiền thưởng nóng, tiền thưởng dự án', 'All staff members were awarded a holiday bonus after record annual sales.'),
      w('incentive', 'n', '/ɪnˈsentɪv/', 'sự khích lệ vật chất, phần thưởng hiệu suất', 'The firm offers financial incentives for employees who cycle to work.'),
      w('commission', 'n', '/kəˈmɪʃn/', 'tiền hoa hồng theo doanh số bán hàng', 'Sales representatives earn a 5% commission on every vehicle sold.'),
      w('deduction', 'n', '/dɪˈdʌkʃn/', 'khoản trừ vào lương (thuế, bảo hiểm xã hội)', 'Check your monthly pay stub to review tax deductions and healthcare withholding.'),
      w('entitlement', 'n', '/ɪnˈtaɪtlmənt/', 'quyền được hưởng (phúc lợi, ngày nghỉ)', 'Full-time staff enjoy an annual leave entitlement of twenty paid business days.'),
      w('paid leave', 'n phr', '/peɪd liːv/', 'nghỉ phép hưởng nguyên lương', 'Maternity leave provides up to twelve weeks of fully paid leave.'),
      w('sick leave', 'n phr', '/sɪk liːv/', 'nghỉ ốm hưởng chế độ bảo hiểm', 'Please notify your direct manager by 8 AM if you need to take sick leave.'),
      w('reimbursement', 'n', '/ˌriːɪmˈbɜːsmənt/', 'sự hoàn trả chi phí đã ứng trước', 'Submit meal receipts within five business days to guarantee prompt reimbursement.'),
      w('pay slip', 'n phr', '/peɪ slɪp/', 'phiếu báo lương chi tiết', 'Electronic pay stubs are accessible through the company internal portal.'),
      w('stock option', 'n phr', '/stɒk ˈɒpʃn/', 'quyền chọn mua cổ phiếu ưu đãi', 'Key engineers were granted stock options that vest over four years.'),
      w('overdue', 'adj', '/ˌəʊvəˈdjuː/', 'quá hạn thanh toán, trễ hạn', 'Salary disbursements for remote contractors are currently two days overdue.'),
      w('subsidy', 'n', '/ˈsʌbsədi/', 'tiền trợ cấp, hỗ trợ kinh phí', 'The enterprise offers a public transit subsidy for daily commuters.'),
      w('allowance', 'n', '/əˈlaʊəns/', 'tiền phụ cấp cố định hằng tháng', 'Expatriate managers receive a generous monthly housing allowance.'),
      w('retroactive', 'adj', '/ˌretrəʊˈæktɪv/', 'có hiệu lực hồi tố ngược về trước', 'The wage hike approved in October will be retroactive to July 1st.'),
      w('gross pay', 'n phr', '/ɡrəʊs peɪ/', 'tổng thu nhập trước thuế', 'Your gross pay includes base wages, overtime, and quarterly commissions.'),
      w('net pay', 'n phr', '/net peɪ/', 'tiền thực lĩnh về tay (sau thuế & khấu trừ)', 'After tax deductions and healthcare withholding, net pay was deposited directly.')
    ]
  },
  {
    id: 7,
    title: 'Mua sắm, Đặt hàng & Quản lý tồn kho (Purchasing, Procurement & Inventory)',
    words: [
      w('procurement', 'n', '/prəˈkjʊəmənt/', 'hoạt động thu mua vật tư, trang thiết bị', 'The procurement department negotiated favorable volume discounts with suppliers.'),
      w('requisition', 'n, v', '/ˌrekwɪˈzɪʃn/', 'phiếu yêu cầu mua sắm vật tư; trưng dụng', 'Please submit an official purchase requisition before ordering new monitors.'),
      w('vendor', 'n', '/ˈvendɔː(r)/', 'nhà cung cấp hàng hóa/dịch vụ', 'We evaluate vendors annually based on pricing, quality, and delivery speed.'),
      w('supplier', 'n', '/səˈplaɪə(r)/', 'nhà cung ứng nguyên vật liệu', 'The auto plant relies on domestic suppliers for high-precision steel components.'),
      w('inventory', 'n', '/ˈɪnvəntri/', 'hàng tồn kho, bản kiểm kê tài sản tồn', 'Warehouse personnel conduct monthly inventory audits to prevent discrepancies.'),
      w('stock', 'n, v', '/stɒk/', 'kho hàng, nguồn dự trữ; tích trữ trong kho', 'The supermarket keeps large stocks of essential canned goods in back storage.'),
      w('purchase order', 'n phr', '/ˈpɜːtʃəs ˈɔːdə(r)/', 'đơn đặt hàng thương mại (PO)', 'Goods will only be dispatched upon receipt of a valid signed purchase order.'),
      w('replenish', 'v', '/rɪˈplenɪʃ/', 'bổ sung hàng vào kho cho đầy lại', 'The grocery manager arranged an expedited shipment to replenish sold-out milk.'),
      w('backorder', 'n, v', '/ˈbækɔːdə(r)/', 'đơn hàng tồn đọng chờ đợt xuất xưởng mới', 'Due to unexpected demand, the popular camera model has been placed on backorder.'),
      w('invoice', 'n, v', '/ˈɪnvɔɪs/', 'hóa đơn thanh toán thương mại', 'Payment is due within thirty calendar days from the date of the invoice.'),
      w('lead time', 'n phr', '/liːd taɪm/', 'thời gian từ lúc đặt hàng đến khi nhận', 'Standard lead time for custom office furniture is approximately six weeks.'),
      w('barcode', 'n', '/ˈbɑːkəʊd/', 'mã vạch quản lý sản phẩm', 'Cashiers scan the barcode on each parcel to log inventory movement in real time.'),
      w('warehouse', 'n', '/ˈweəhaʊs/', 'kho hàng chứa sản phẩm/vật tư', 'The automated distribution warehouse can process ten thousand orders daily.'),
      w('fulfill', 'v', '/fʊlˈfɪl/', 'hoàn tất và giao đơn đặt hàng', 'Our fulfillment center works 24/7 to fulfill holiday online purchases promptly.'),
      w('surplus stock', 'n phr', '/ˈsɜːpləs stɒk/', 'lượng hàng tồn kho dư thừa', 'Surplus stock was auctioned off at deep discounts to free up shelf space.'),
      w('deplete', 'v', '/dɪˈpliːt/', 'làm cạn kiệt nguồn cung tồn kho', 'Heavy storm buying rapidly depleted local stocks of bottled water.'),
      w('quote', 'n, v', '/kwəʊt/', 'bản báo giá dự toán; báo giá', 'We requested competitive price quotes from three rival printing contractors.'),
      w('specifications', 'n (pl)', '/ˌspesɪfɪˈkeɪʃnz/', 'thông số kỹ thuật chi tiết của hàng hóa', 'Supplied computer chips must comply with exact engineering specifications.'),
      w('bulk order', 'n phr', '/bʌlk ˈđɪskaʊnt/', 'đơn đặt hàng số lượng lớn để nhận chiết khấu', 'Clients placing a bulk order of 500 units receive free transatlantic shipping.'),
      w('pallet', 'n', '/ˈpælət/', 'tấm nâng hàng, kệ kê hàng trong kho', 'Forklifts unloaded twenty wooden pallets of ceramic tiles from the semi-truck.'),
      w('batch', 'n', '/bætʃ/', 'lô hàng, mẻ sản phẩm', 'Quality control inspectors rejected a batch of fabric due to uneven dyeing.'),
      w('defective', 'adj', '/dɪˈfektɪv/', 'bị lỗi kỹ thuật, hỏng hóc', 'The manufacturer agreed to replace all defective electronic components immediately.'),
      w('distributor', 'n', '/dɪˈstrɪbjətə(r)/', 'nhà phân phối độc quyền/khu vực', 'The Japanese brewery partnered with a national distributor across North America.'),
      w('out of stock', 'idiom', '/aʊt əv stɒk/', 'hết hàng trong kho', 'This particular size is currently out of stock but will arrive next Tuesday.'),
      w('overstock', 'v, n', '/ˌəʊvəˈstɒk/', 'ôm quá nhiều hàng, tích trữ dư thừa', 'Retailers often hold clearance sales when seasonal clothing is overstocked.'),
      w('bill of materials', 'n phr', '/bɪl əv məˈtɪəriəlz/', 'bảng định mức nguyên vật liệu sản xuất', 'Engineers finalized the comprehensive bill of materials for the new electric sedan.'),
      w('consignment', 'n', '/kənˈsaɪnmənt/', 'lô hàng ký gửi ủy thác', 'The consignment of Swiss watches arrived safely at the port of Rotterdam.'),
      w('turnaround time', 'n phr', '/ˈtɜːnəraʊnd taɪm/', 'thời gian xử lý hoàn tất một đơn hàng', 'The lab boasts a 24-hour turnaround time for processing urgent blood tests.'),
      w('manifest', 'n', '/ˈmænɪfest/', 'bản kê khai hàng hóa vận tải', 'Customs agents inspected the cargo manifest before granting port clearance.'),
      w('shortage', 'n', '/ˈʃɔːtɪdʒ/', 'sự khan hiếm hàng hóa trên thị trường', 'A global semiconductor shortage delayed new automobile deliveries for months.')
    ]
  },
  {
    id: 8,
    title: 'Giao nhận, Vận chuyển & Kho vận (Shipping, Freight & Logistics)',
    words: [
      w('freight', 'n', '/freɪt/', 'hàng hóa vận chuyển bằng tàu/máy bay, cước phí', 'Air freight is substantially faster but more expensive than ocean transport.'),
      w('carrier', 'n', '/ˈkæriə(r)/', 'công ty vận tải, đơn vị chuyên chở', 'Our preferred ocean carrier operates regular routes between Busan and Long Beach.'),
      w('transit', 'n', '/ˈtrænzɪt/', 'quá trình vận chuyển trên đường', 'Goods damaged in transit will be replaced at no additional cost to the customer.'),
      w('dispatch', 'v, n', '/dɪˈspætʃ/', 'gửi đi, điều phối xuất phát; sự phái đi', 'The fleet supervisor dispatched three delivery trucks at dawn this morning.'),
      w('courier', 'n', '/ˈkʊriə(r)/', 'nhân viên chuyển phát nhanh thư từ/bưu phẩm', 'A motorcycle courier delivered the urgent legal contracts directly to the courthouse.'),
      w('customs', 'n (pl)', '/ˈkʌstəmz/', 'cơ quan hải quan, thủ tục hải quan', 'All imported electronics must undergo thorough clearance by federal customs.'),
      w('tariff', 'n', '/ˈtærɪf/', 'thuế quan đánh vào hàng nhập khẩu', 'New tariffs imposed on imported solar panels affected domestic installation prices.'),
      w('tracking number', 'n phr', '/ˈtrækɪŋ ˈnʌmbə(r)/', 'mã số tra cứu bưu phẩm vận chuyển', 'Customers receive an automated email containing their parcel tracking number.'),
      w('cargo', 'n', '/ˈkɑːɡəʊ/', 'kiện hàng, hàng hóa chở trên tàu/máy bay', 'The container ship was carrying heavy industrial cargo bound for Shanghai.'),
      w('fragile', 'adj', '/ˈfrædʒaɪl/', 'dễ vỡ, cần bốc xếp nhẹ tay', 'Please affix "Fragile: Handle With Care" stickers on all glassware cartons.'),
      w('perishable', 'adj, n', '/ˈperɪʃəbl/', 'dễ hư hỏng, mau ôi thiu (thực phẩm)', 'Perishable goods like fresh dairy must be transported in refrigerated containers.'),
      w('bill of lading', 'n phr', '/bɪl əv ˈleɪdɪŋ/', 'vận đơn đường biển (B/L)', 'The buyer must present the original bill of lading to claim goods at the terminal.'),
      w('vessel', 'n', '/ˈvesl/', 'tàu thủy chở hàng cỡ lớn', 'The ocean vessel anchored outside the harbor waiting for an available docking berth.'),
      w('demurrage', 'n', '/dɪˈmʌrɪdʒ/', 'phí lưu kho bãi, phí phạt dỡ hàng trễ hạn', 'The importer incurred steep demurrage fees after shipping containers sat idle for days.'),
      w('dock', 'n, v', '/dɒk/', 'bến tàu dỡ hàng; cập bến neo đậu', 'The container ship is scheduled to dock at Terminal 4 tomorrow morning.'),
      w('expedite', 'v', '/ˈekspədaɪt/', 'xúc tiến đẩy nhanh tiến độ vận chuyển', 'We paid an additional surcharge to expedite delivery of replacement machine parts.'),
      w('hauler', 'n', '/ˈhɔːlə(r)/', 'đơn vị kéo xe chở hàng đường dài', 'Local haulers transport freight from the rail depot to neighborhood retail centers.'),
      w('overland', 'adj, adv', '/ˈəʊvəlænd/', 'bằng đường bộ (xe tải, xe lửa)', 'Overland transport across the continent takes approximately five business days.'),
      w('stowage', 'n', '/ˈstəʊɪdʒ/', 'sự sắp xếp xếp dỡ hàng vào khoang tàu', 'Improper stowage caused severe cargo shifts during the severe North Sea gale.'),
      w('fleet', 'n', '/fliːt/', 'đội xe tải/đội tàu vận chuyển hàng', 'The logistics corporation recently modernized its entire fleet of electric vans.'),
      w('drop-ship', 'v', '/drɒp ʃɪp/', 'giao hàng trực tiếp từ xưởng đến khách', 'Many online retailers drop-ship merchandise straight from factories to customers.'),
      w('clearance', 'n', '/ˈklɪərəns/', 'sự thông quan hải quan; giấy phép', 'Shipments cannot leave port premises until customs clearance is formally granted.'),
      w('transshipment', 'n', '/trænsˈʃɪpmənt/', 'sự chuyển tải sang tàu/phương tiện khác', 'Singapore serves as a premier transshipment hub connecting Asia and Europe.'),
      w('depot', 'n', '/ˈdepəʊ/', 'trạm tập kết xe, kho trung chuyển hàng', 'Delivery vans return to the central depot each evening for recharging and refueling.'),
      w('intermodal', 'adj', '/ˌɪntəˈməʊdl/', 'vận tải đa phương thức kết hợp', 'Intermodal freight transport combines rail, trucking, and container shipping.'),
      w('haul', 'v, n', '/hɔːl/', 'vận chuyển cự ly xa; quãng đường chở hàng', 'Long-haul freight drivers adhere strictly to mandatory rest period regulations.'),
      w('waybill', 'n', '/ˈweɪbɪl/', 'vận đơn hàng không / đường sắt', 'The air waybill serves as an official receipt between the shipper and carrier.'),
      w('stevedore', 'n', '/ˈstiːvədɔː(r)/', 'công nhân bốc xếp cảng biển', 'Experienced stevedores operated heavy cranes to unload giant 40-foot containers.'),
      w('logistics', 'n', '/ləˈdʒɪstɪks/', 'ngành hậu cần kho vận', 'Streamlining corporate logistics cut distribution overhead by twenty percent.'),
      w('consigned', 'adj', '/kənˈsaɪnd/', 'được ủy thác gửi giao cho ai', 'The consigned shipment arrived in immaculate condition without any carton damage.')
    ]
  },
  {
    id: 9,
    title: 'Dịch vụ khách hàng, Bảo hành & Khiếu nại (Customer Service & Complaints)',
    words: [
      w('complaint', 'n', '/kəmˈpleɪnt/', 'lời phàn nàn, khiếu nại của khách', 'The customer service team promptly addressed the client’s complaint about late delivery.'),
      w('warranty', 'n', '/ˈwɒrənti/', 'giấy bảo hành, cam kết bảo hành sản phẩm', 'All new home appliances come with a comprehensive two-year manufacturer warranty.'),
      w('refund', 'n, v', '/ˈriːfʌnd/', 'tiền hoàn lại; hoàn trả lại tiền', 'Customers who receive damaged items are eligible for a complete cash refund.'),
      w('courtesy', 'n', '/ˈkɜːtəsi/', 'sự lịch thiệp nhã nhặn; quà tặng kèm miễn phí', 'As a courtesy to delayed passengers, the airline provided complimentary lunch vouchers.'),
      w('patron', 'n', '/ˈpeɪtrən/', 'khách hàng quen, thân chủ thường xuyên', 'The prestigious hotel rewards loyal patrons with room upgrades and spa credits.'),
      w('feedback', 'n', '/ˈfiːdbæk/', 'ý kiến phản hồi đóng góp của khách hàng', 'We actively encourage customer feedback to refine our online checkout experience.'),
      w('representative', 'n', '/ˌreprɪˈzentətɪv/', 'đại diện dịch vụ hỗ trợ khách hàng', 'Please stay on the line; a customer support representative will assist you shortly.'),
      w('inquiry', 'n', '/ɪnˈkwaɪəri/', 'thắc mắc, câu hỏi tìm hiểu thông tin', 'Our support desk handles inquiries regarding product availability and billing.'),
      w('replacement', 'n', '/rɪˈpleɪsmənt/', 'sản phẩm thay thế, sự đổi mới', 'The store offered an immediate replacement for the defective wireless earphones.'),
      w('dissatisfaction', 'n', '/dɪsˌsætɪsˈfækʃn/', 'sự không hài lòng, thất vọng', 'Management issued an apology following customer dissatisfaction with the delayed app update.'),
      w('prompt', 'adj', '/prɒmpt/', 'nhanh chóng, mau lẹ kịp thời', 'We take pride in providing prompt and courteous responses to client emails.'),
      w('guarantee', 'n, v', '/ˌɡærənˈtiː/', 'sự bảo đảm; cam đoan chất lượng', 'Our money-back guarantee allows buyers to test the software risk-free for 30 days.'),
      w('redress', 'n, v', '/rɪˈdres/', 'sự bồi thường thỏa đáng; đền bù thiệt hại', 'The consumer protection agency helps victims seek redress against misleading claims.'),
      w('hotline', 'n', '/ˈhɒtlaɪn/', 'đường dây nóng hỗ trợ khẩn cấp', 'The technical support hotline operates twenty-four hours a day, seven days a week.'),
      w('dispute', 'n, v', '/dɪˈspjuːt/', 'tranh chấp giao dịch, bất đồng ý kiến', 'Cardholders can dispute unauthorized charges directly through their online portal.'),
      w('apology', 'n', '/əˈpɒlədʒi/', 'lời xin lỗi chân thành từ doanh nghiệp', 'The airline offered a sincere public apology for widespread holiday cancellations.'),
      w('responsive', 'adj', '/rɪˈspɒnsɪv/', 'phản hồi nhanh nhạy, biết lắng nghe', 'Our technical support staff is extraordinarily responsive to urgent client tickets.'),
      w('clientele', 'n', '/ˌkliːənˈtel/', 'tập khách hợp đồng, nhóm khách hàng quen', 'The luxury resort caters to an affluent international corporate clientele.'),
      w('inoperable', 'adj', '/ɪnˈɒprəbl/', 'không hoạt động được, bị hỏng hóc', 'Customers may return inoperable electronic gadgets within thirty days for replacement.'),
      w('troubleshoot', 'v', '/ˈtrʌblʃuːt/', 'khắc phục sự cố, tìm nguyên nhân lỗi', 'The user manual features a troubleshooting guide for common connection glitches.'),
      w('recourse', 'n', '/rɪˈkɔːs/', 'sự viện đến quyền pháp lý, phương sách bảo vệ', 'Dissatisfied consumers have legal recourse through the state arbitration bureau.'),
      w('goodwill', 'n', '/ˌɡʊdˈwɪl/', 'thiện chí thương mại, uy tín thương hiệu', 'As a gesture of goodwill, the manager waived the standard table reservation fee.'),
      w('compensate', 'v', '/ˈkɒmpenseɪt/', 'đền bù thỏa đáng tổn thất cho khách', 'The carrier compensated affected travelers with free international round-trip tickets.'),
      w('satisfaction survey', 'n phr', '/sætɪsˈfækʃn ˈsɜːveɪ/', 'khảo sát mức độ hài lòng khách hàng', 'Please take two minutes to fill out our post-service satisfaction survey.'),
      w('escalate', 'v', '/ˈeskəleɪt/', 'chuyển vụ việc khiếu nại lên cấp cao hơn', 'If the front desk cannot resolve the issue, the supervisor will escalate the ticket.'),
      w('remedy', 'n, v', '/ˈremədi/', 'biện pháp khắc phục sửa chữa sai sót', 'The company took immediate legal remedies to rectify the billing error.'),
      w('negligence', 'n', '/ˈneɡlɪdʒəns/', 'sự tắc trách cẩu thả gây thiệt hại', 'The hotel was accused of gross negligence after failing to salt the icy walkway.'),
      w('unattended', 'adj', '/ˌʌnəˈtendɪd/', 'bị bỏ mặc không ai để mắt hỗ trợ', 'Customer support tickets should never remain unattended for over four hours.'),
      w('toll-free', 'adj, adv', '/ˌtəʊl ˈfriː/', 'miễn cước cuộc gọi viễn thông', 'Customers calling from within North America may dial our toll-free support line.'),
      w('restitution', 'n', '/ˌrestɪˈtjuːʃn/', 'sự bồi hoàn thỏa đáng thiệt hại cho khách', 'The manufacturer offered full restitution for damages caused by the inoperable appliance.')
    ]
  },
  {
    id: 10,
    title: 'Công nghệ thông tin & Phần mềm văn phòng (IT, Software & Systems)',
    words: [
      w('database', 'n', '/ˈdeɪtəbeɪs/', 'cơ sở dữ liệu thông tin số', 'All customer transaction records are stored securely in an encrypted cloud database.'),
      w('backup', 'n, v', '/ˈbækʌp/', 'sao lưu dữ liệu phòng ngừa sự cố; bản sao', 'IT policy requires staff to perform daily backups of all critical spreadsheets.'),
      w('compatibility', 'n', '/kəmˌpætəˈbɪləti/', 'tính tương thích giữa các hệ thống phần mềm', 'Before migrating to the new operating system, we tested compatibility with legacy apps.'),
      w('glitch', 'n', '/ɡlɪtʃ/', 'trục trặc kỹ thuật nhỏ, lỗi gián đoạn', 'A temporary software glitch prevented users from downloading their invoices yesterday.'),
      w('upgrade', 'v, n', '/ˌʌpˈɡreɪd/', 'nâng cấp phần cứng/phần mềm; bản nâng cấp', 'The company plans to upgrade all employee laptops to high-speed solid-state drives.'),
      w('configuration', 'n', '/kənˌfɪɡəˈreɪʃn/', 'cấu hình thiết bị/hệ thống mạng', 'Network engineers adjusted the router configuration to boost office bandwidth.'),
      w('cybersecurity', 'n', '/ˈsaɪbəsɪkjʊərəti/', 'an ninh mạng, bảo mật thông tin số', 'The bank invests heavily in cutting-edge cybersecurity to thwart malicious hacking.'),
      w('bandwidth', 'n', '/ˈbændwɪdθ/', 'băng thông đường truyền mạng', 'Video conferencing requires high bandwidth to prevent annoying audio lag.'),
      w('server', 'n', '/ˈsɜːvə(r)/', 'máy chủ lưu trữ và vận hành mạng', 'The central server undergoes scheduled maintenance every Sunday at midnight.'),
      w('outage', 'n', '/ˈaʊtɪdʒ/', 'sự mất điện, sự sập nguồn mạng diện rộng', 'A sudden power surge caused a three-hour internet outage across headquarters.'),
      w('credentials', 'n (pl)', '/krəˈdenʃlz/', 'thông tin đăng nhập bảo mật (user/pass)', 'Never share your corporate login credentials with anyone outside the organization.'),
      w('firewall', 'n', '/ˈfaɪəwɔːl/', 'bức tường lửa ngăn chặn xâm nhập trái phép', 'The corporate firewall blocks unauthorized downloads and suspicious external traffic.'),
      w('protocol', 'n', '/ˈprəʊtəkɒl/', 'giao thức truyền thông mạng, quy chuẩn', 'All cloud communications follow secure HTTPS and cryptographic transfer protocols.'),
      w('deploy', 'v', '/dɪˈplɔɪ/', 'triển khai ứng dụng/hệ thống vào hoạt động', 'The development team will deploy the new billing software patch this weekend.'),
      w('cloud computing', 'n phr', '/klaʊd kəmˈpjuːtɪŋ/', 'điện toán đám mây', 'Migrating to cloud computing eliminated the need for costly on-premise servers.'),
      w('malware', 'n', '/ˈmælweə(r)/', 'phần mềm độc hại, virus phá hoại', 'Antivirus scans detected and quarantined malicious malware on the marketing terminal.'),
      w('phishing', 'n', '/ˈfɪʃɪŋ/', 'hình thức lừa đảo giả mạo qua email', 'Employees must complete annual training to identify sophisticated phishing attempts.'),
      w('portal', 'n', '/ˈpɔːtl/', 'cổng thông tin điện tử nội bộ/khách hàng', 'Employees can submit expense claims directly through the corporate intranet portal.'),
      w('interface', 'n', '/ˈɪntəfeɪs/', 'giao diện người dùng', 'The updated mobile app features an intuitive, user-friendly graphical interface.'),
      w('hardware', 'n', '/ˈhɑːdweə(r)/', 'phần cứng máy tính, linh kiện thiết bị', 'The IT department is responsible for repairing faulty office hardware.'),
      w('software patch', 'n phr', '/ˈsɒftweə pætʃ/', 'bản vá lỗi phần mềm', 'Security administrators strongly urge users to install the critical software patch.'),
      w('authenticate', 'v', '/ɔːˈθentɪkeɪt/', 'xác thực danh tính đăng nhập', 'Two-factor authentication is required to access sensitive financial databases.'),
      w('encrypt', 'v', '/ɪnˈkrɪpt/', 'mã hóa dữ liệu bảo mật', 'Personal data must be encrypted before transmission over public internet networks.'),
      w('reboot', 'v, n', '/ˌriːˈbuːt/', 'khởi động lại hệ thống máy móc', 'Try rebooting your workstation if the word processing application freezes.'),
      w('telecommute', 'v', '/ˌtelikəˈmjuːt/', 'làm việc từ xa qua mạng internet', 'Over half of our graphic designers telecommute three days per week.'),
      w('latency', 'n', '/ˈleɪtənsi/', 'độ trễ tín hiệu đường truyền', 'Fiber-optic cables significantly reduce data transmission latency.'),
      w('bug', 'n', '/bʌɡ/', 'lỗi code trong phần mềm', 'Programmers worked overtime to squash critical bugs before the official product launch.'),
      w('automation', 'n', '/ˌɔːtəˈmeɪʃn/', 'sự tự động hóa quy trình phần mềm', 'Robotic process automation reduced repetitive data-entry workloads by 70%.'),
      w('downtime', 'n', '/ˈdaʊntaɪm/', 'thời gian hệ thống ngừng hoạt động', 'Unscheduled server downtime costs the e-commerce retailer thousands of dollars per minute.'),
      w('tech support', 'n phr', '/tek səˈpɔːt/', 'hỗ trợ kỹ thuật phần mềm/phần cứng', 'Contact tech support immediately if you encounter error code 503.')
    ]
  },
  {
    id: 11,
    title: 'Thiết bị văn phòng, Máy móc & Vật tư (Office Equipment & Supplies)',
    words: [
      w('photocopier', 'n', '/ˈfəʊtəʊkɒpiə(r)/', 'máy photocopy văn phòng', 'The modern photocopier can scan double-sided documents at sixty pages per minute.'),
      w('shredder', 'n', '/ˈʃredə(r)/', 'máy hủy tài liệu bảo mật', 'Discarded financial statements must be destroyed immediately in the paper shredder.'),
      w('toner', 'n', '/ˈtəʊnə(r)/', 'mực in dạng bột cho máy in laser', 'Please replace the black toner cartridge before printing the final annual reports.'),
      w('cartridge', 'n', '/ˈkɑːtrɪdʒ/', 'hộp mực máy in, cuộn băng mực', 'The administrative assistant ordered twenty replacement ink cartridges for the office.'),
      w('stationery', 'n', '/ˈsteɪʃənri/', 'văn phòng phẩm (giấy, bút, kẹp, bìa)', 'Our stationery closet is stocked with notebooks, highlighters, and sticky notes.'),
      w('stapler', 'n', '/ˈsteɪplə(r)/', 'cái dập ghim văn phòng', 'Please staple the invoice to the shipping manifest before filing.'),
      w('paper jam', 'n phr', '/ˈpeɪpə dʒæm/', 'kẹt giấy trong máy in', 'Open the side panel of printer B to clear the paper jam.'),
      w('dispenser', 'n', '/dɪˈspensə(r)/', 'hộp đựng tự động (băng keo, nước sát khuẩn)', 'A tape dispenser and scissors are available on the packing station desk.'),
      w('laminate', 'v', '/ˈlæmɪneɪt/', 'ép nhựa màng bảo vệ tài liệu', 'All factory visitor badges must be laminated to prevent wear and tear.'),
      w('scanner', 'n', '/ˈskænə(r)/', 'máy quét tài liệu số hóa', 'Use the high-resolution flatbed scanner to digitize signed contract pages.'),
      w('projector', 'n', '/prəˈdʒektə(r)/', 'máy chiếu slide thuyết trình', 'The meeting room is equipped with an overhead digital projector and drop-down screen.'),
      w('binder', 'n', '/ˈbaɪndə(r)/', 'bìa còng lưu trữ tài liệu', 'Audit records are neatly organized in labeled three-ring binders on shelf four.'),
      w('filing cabinet', 'n phr', '/ˈfaɪlɪŋ ˈkæbɪnət/', 'tủ đựng hồ sơ tài liệu', 'Confidential employee personnel files are locked safely in the metal filing cabinet.'),
      w('consumable', 'n', '/kənˈsjuːməbl/', 'vật tư tiêu hao (giấy in, bút, kẹp)', 'The office manager tracks quarterly spending on consumables like printing paper.'),
      w('ergonomic', 'adj', '/ˌɜːɡəˈnɒmɪk/', 'thiết kế công thái học (chống đau lưng, cổ)', 'Management supplied ergonomic mesh chairs to enhance employee posture and comfort.'),
      w('workstation', 'n', '/ˈwɜːksteɪʃn/', 'vị trí bàn làm việc cá nhân của nhân viên', 'Each workstation includes dual monitors, an adjustable desk, and high-speed internet.'),
      w('malfunction', 'v, n', '/ˌmælˈfʌŋkʃn/', 'gặp sự cố trục trặc kỹ thuật; sự hỏng hóc', 'If the thermal label printer malfunctions, notify facilities immediately.'),
      w('maintenance contract', 'n phr', '/ˈmeɪntənəns ˈkɒntrækt/', 'hợp đồng bảo dưỡng thiết bị định kỳ', 'Our copier maintenance contract includes complimentary toner and quarterly servicing.'),
      w('appliance', 'n', '/əˈplaɪəns/', 'thiết bị gia dụng văn phòng (lò vi sóng, ấm)', 'The breakroom is equipped with a refrigerator, microwave, and coffee appliance.'),
      w('laminator', 'n', '/ˈlæmɪneɪtə(r)/', 'máy ép màng nhựa tài liệu', 'The administrative assistant loaded new thermal pouches into the laminator.'),
      w('paper clip', 'n phr', '/ˈpeɪpə klɪp/', 'kẹp ghim giấy kim loại', 'Use a paper clip rather than staples so original certificates are not punctured.'),
      w('whiteboard', 'n', '/ˈwaɪtbɔːd/', 'bảng trắng viết bút lông để họp', 'The brainstorm team sketched out product wireframes across the giant whiteboard.'),
      w('easel', 'n', '/ˈiːzl/', 'giá đỡ bảng vẽ, giá kẹp flipchart', 'Meeting organizers set up a presentation easel beside the podium.'),
      w('receptacle', 'n', '/rɪˈseptəkl/', 'thùng chứa rác, ổ cắm điện', 'Discard recyclable aluminum soda cans into the green receptacle near the kitchen.'),
      w('shred', 'v', '/ʃred/', 'xé nhỏ tài liệu, cắt vụn bảo mật', 'Regulations mandate that outdated customer credit slips be shredded completely.'),
      w('supply closet', 'n phr', '/səˈplaɪ ˈklɒzɪt/', 'kho/tủ chứa văn phòng phẩm', 'Extra reams of A4 paper are stacked inside the second-floor supply closet.'),
      w('cubicle', 'n', '/ˈkjuːbɪkl/', 'ngăn phòng làm việc dạng ô', 'The open-plan office layout was replaced with soundproof cubicles for better focus.'),
      w('apparatus', 'n', '/ˌæpəˈreɪtəs/', 'bộ máy thiết bị chuyên dụng', 'Technicians tested the air filtration apparatus before opening the cleanroom.'),
      w('out of order', 'idiom', '/aʊt əv ˈɔːdə(r)/', 'bị hỏng ngưng hoạt động', 'The fourth-floor elevator is temporarily out of order for routine cable inspection.'),
      w('wear and tear', 'idiom', '/weə(r) ənd teə(r)/', 'sự hao mòn tự nhiên do sử dụng', 'The lease covers normal wear and tear on office carpeting and painted walls.')
    ]
  }
];
